### ISSUE TITLE
Show with TabbedShowLayout is not rendering contents of Tabs

### ISSUE THREAD

**Issue by zifnab87** [marmelab/admin-on-rest#1145] opened 2017-10-11 14:58 UTC
Please do not submit support requests or "How to" questions here. For that, go to [StackOverflow](http://stackoverflow.com/questions/tagged/admin-on-rest).

**What you were expecting:**
Rendering of  tab contents in Show

**What happened instead:**
Nothing was rendered

**Steps to reproduce:**
I followed the users example here: https://github.com/marmelab/admin-on-rest/blob/49a616c93d1ee5ea0bfa3c5f7abea0bb29c8d01c/example/users.js#L136

```
<Show {...props} title={<PVPlantTitle/>}>
   <TabbedShowLayout >
        <Tab label="Analytics">
            <TextField source="id" />
            <TextField source="name" />
        </Tab>
    </TabbedShowLayout>
</Show>
```

**Other information:**

![image](https://user-images.githubusercontent.com/526062/31448640-9e7071e4-aead-11e7-91ce-26a2919a2396.png)

**Environment**

* Admin-on-rest version: 1.3.2
* Last version that did not exhibit the issue (if applicable):
* React version: ~15.5.4
* Browser: all
* Stack trace (in case of a JS error): 

```
proxyConsole.js:56 Warning: Unknown props record, basePath on <button> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in button (created by EnhancedButton)
    in EnhancedButton (created by Tab)
    in Tab (at pvplants.js:130)
    in div (created by TabTemplate)
    in TabTemplate (created by Tabs)
    in div (created by Tabs)
    in div (created by Tabs)
    in Tabs (created by TabbedShowLayout)
    in div (created by TabbedShowLayout)
    in TabbedShowLayout (created by Connect(TabbedShowLayout))
    in Connect(TabbedShowLayout) (at pvplants.js:129)
    in div (created by Card)
    in div (created by Paper)
    in Paper (created by Card)
    in Card (created by Show)
    in div (created by Show)
    in Show (created by WithPermissionsFilteredChildren)
    in WithPermissionsFilteredChildren (created by getContext(WithPermissionsFilteredChildren))
    in getContext(WithPermissionsFilteredChildren) (created by getContext(getContext(WithPermissionsFilteredChildren)))
    in getContext(getContext(WithPermissionsFilteredChildren)) (created by Connect(getContext(getContext(WithPermissionsFilteredChildren))))
    in Connect(getContext(getContext(WithPermissionsFilteredChildren))) (at pvplants.js:128)
    in PVPlantShow (created by Route)
    in Restricted (created by Connect(Restricted))
    in Connect(Restricted) (created by Route)
    in Route (created by CrudRoute)
    in Switch (created by CrudRoute)
    in CrudRoute (created by Route)
    in Route (created by AdminRoutes)
    in Switch (created by AdminRoutes)
    in AdminRoutes (created by Connect(AdminRoutes))
    in Connect(AdminRoutes) (created by getContext(Connect(AdminRoutes)))
    in getContext(Connect(AdminRoutes)) (at Layout.js:75)
    in div (at Layout.js:74)
    in div (at Layout.js:73)
    in div (at Layout.js:69)
    in div (at Layout.js:68)
    in MuiThemeProvider (at Layout.js:67)
    in Layout (created by Connect(Layout))
    in Connect(Layout) (created by Route)
    in Route (created by Admin)
    in Switch (created by Admin)
    in div (created by Admin)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Admin)
    in TranslationProvider (created by withContext(TranslationProvider))
    in withContext(TranslationProvider) (created by Connect(withContext(TranslationProvider)))
    in Connect(withContext(TranslationProvider)) (created by Admin)
    in Provider (created by Admin)
    in Admin (created by withContext(Admin))
    in withContext(Admin) (at App.js:38)
    in App (at index.js:15)
```

**Comment by fzaninotto** [comment] 2017-10-11 15:28
Can't reproduce on [the example](https://github.com/marmelab/admin-on-rest/blob/master/example/posts.js#L252) with aor 1.3.2 and React ~15.6. There must be something else in your setup that causes the bug. 

Can you fork https://codesandbox.io/s/ElxGNxBY0, to try and reproduce your issue?

**Comment by zifnab87** [comment] 2017-10-11 18:27
ok I will try to reproduce it! thanks

**Comment by zifnab87** [comment] 2017-10-12 13:09
I was using Tab from material-ui instead of admin-on-rest - I wish there was a way to differentiate components coming directly from material-ui and enhanced ones from admin-on-rest
Here is the reproduction sandbox:
https://codesandbox.io/s/4wkk04low4

**Comment by fzaninotto** [comment] 2017-10-12 14:00
Understood. As there is no bug in admin-on-rest, I'm closing this issue.

**Closed by fzaninotto** 2017-10-12 14:00 UTC
