### ISSUE TITLE
ReferenceInput error on IE11: Object doesn't support property or method 'from'

### ISSUE THREAD

**Issue by GencBlakqori** [marmelab/admin-on-rest#1708] opened 2018-03-29 13:58 UTC
I am trying to use the ReferenceInput in my project for some relation.
It works fine on Chrome, Firefox ... but doesn't work on IE11. It keeps saying:

_**uncaught at anonymous TypeError: Object doesn't support property or method 'from'**_

Code snippet:
```
<ReferenceInput label="User" source="user_id" reference="users" allowEmpty>
  <SelectInput optionText="name" />
</ReferenceInput>
```

I have the 'users' end point available. I use it elsewhere as well.

Full error stack:
```
_uncaught at anonymous TypeError: Object doesn't support property or method 'from'
   at t.getPossibleReferences
   at o
   at n.displayName
   at i
   at s
   at Anonymous function 
   at n.run
   at c.prototype.componentWillReceiveProps
   at updateClassInstance
   at beginWor_
```

**Comment by fzaninotto** [comment] 2018-03-29 14:06
The culprit is:

https://github.com/marmelab/admin-on-rest/blob/d811384be4e909f05e781abd50585b38740f52cc/src/reducer/admin/references/possibleValues.js#L39-L41

How do you transpile/bundle the admin-on-rest code?

**Comment by GencBlakqori** [comment] 2018-03-29 14:56
I use the default **npm run build** that executes **react-scripts build**. I don't do anything else.

**Comment by fzaninotto** [comment] 2018-03-29 15:02
You mean you're using `create-react-app`?

**Comment by fzaninotto** [comment] 2018-03-30 15:35
So you're using `create-react-app` (but you don't know it). It seems that the babel JS transpilation configured in this version of create-react-app doesn't target the right platform, but [it should](http://kangax.github.io/compat-table/es6/#test-Array.from). I believe you're using an old version of create-react-app and need to upgrade.

I can't reproduce the error on the demo (https://marmelab.com/admin-on-rest-demo/#/products/128) on ie11. The demo also uses create-react-app.

Closing as not reproducible. Feel free to reopen if you can provide a minimal codesandbox with the error.

**Closed by fzaninotto** 2018-03-30 15:35 UTC

**Comment by GencBlakqori** [comment] 2018-04-03 09:22
@fzaninotto I updated create-react-app. It changed the error, but I'm still not able to get it work. Now I'm getting something else:
```
uncaught at anonymous TypeError: Unable to get property 'return' of undefined or null reference
   at renderRoot (http://localhost:3000/static/js/bundle.js:98523:9)
   at performWorkOnRoot (http://localhost:3000/static/js/bundle.js:99064:9)
   at performWork (http://localhost:3000/static/js/bundle.js:98985:9)
   at performSyncWork (http://localhost:3000/static/js/bundle.js:98962:5)
   at requestWork (http://localhost:3000/static/js/bundle.js:98862:7)
   at scheduleWorkImpl (http://localhost:3000/static/js/bundle.js:98737:13)
   at scheduleWork (http://localhost:3000/static/js/bundle.js:98697:5)
   at updater.enqueueSetState (http://localhost:3000/static/js/bundle.js:93336:7)
   at Component.prototype.setState (http://localhost:3000/static/js/bundle.js:117880:3)
   at onStateChange (http://localhost:3000/static/js/bundle.js:111428:11)
   at notify (http://localhost:3000/static/js/bundle.js:112087:9)
   at notifyNestedSubs (http://localhost:3000/static/js/bundle.js:112126:5)
   at onStateChange (http://localhos
```
The code is again the same as above, so nothing else really. And, it's only happening on IE ( on chrome it's working fine ).

**Comment by fzaninotto** [comment] 2018-04-03 10:06
It's impossible to debug your problem using this stack trace. And again, it works on the demo, so the problem is probably on your side. 

Please use StackOverflow for troubleshooting.

**Comment by GencBlakqori** [comment] 2018-04-03 10:29
Is the code of the Demo on Github available?

**Comment by fzaninotto** [comment] 2018-04-03 10:44
* for master: https://github.com/marmelab/admin-on-rest
* for next: https://github.com/marmelab/admin-on-rest/tree/next/examples/demo
