### ISSUE TITLE
Is custom action of <List> workable?

### ISSUE THREAD

**Issue by winglight** [marmelab/admin-on-rest#1473] opened 2018-02-04 15:10 UTC
I'm trying to add a button on the top of the <List>, then I copied the sample code like this:
```
import { showNotification, CardActions, CreateButton, FlatButton, NavigationRefresh} from 'admin-on-rest';

const cardActionStyle = {
    zIndex: 2,
    display: 'inline-block',
    float: 'right',
};

const PostActions = ({ resource, filters, displayedFilters, filterValues, basePath, showFilter, refresh }) => (
    <CardActions style={cardActionStyle}>
        {filters && React.cloneElement(filters, { resource, showFilter, displayedFilters, filterValues, context: 'button' }) }
        <CreateButton basePath={basePath} />
        <FlatButton primary label="refresh" onClick={refresh} icon={<NavigationRefresh />} />
        {/* Add your custom actions */}
        <FlatButton primary label="Custom Action" onClick={customAction} />
    </CardActions>
);

export const PostList = (props) => (
    <List {...props} actions={<PostActions />}>
        ...
    </List>
);
```

I found the problems as followed:
1. refresh is undefined since the import works fine
2. customAction should be a function, I guess, so I declare a function like this:
```
const customAction = function () {
    fetch('/crawler', { method: 'GET'})
        .then(() => {
            showNotification('Crawled All!');
        })
        .catch((e) => {
            console.error(e);
            showNotification('Error: crawle all', 'warning')
        });
}
```
But there's the same error like "refresh", here's error messages:
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `ListActions`.

I knew the custom button could do the same job but it's complicated to my requirement that's just to call a API and show a message of result.
So any hint will be appreciated!

**Comment by fzaninotto** [comment] 2018-02-04 20:18
The problem is that the syntax of the Refresh button has changed in #942, but this change was not reflected in the documentation. Marking this as a bug, since we need to fix the doc.

Ping @djhi

**Comment by winglight** [comment] 2018-02-05 00:58
@fzaninotto thanks a lot. The first problem is solved.
And how to code that customAction? It's not supported in this way?

**Closed** 2018-02-05 09:25 UTC
Labels: bug
