### ISSUE TITLE
All field need label prop

### ISSUE THREAD

**Issue by ngonhan2k5** [marmelab/admin-on-rest#175] opened 2016-12-07 03:17 UTC
To change Column header text for Datagrid

**Comment by fzaninotto** [comment] 2016-12-21 13:40
No, normally fields use humanized source as default label when `label` isn't provided. 

I'm closing this as I can't reproduce the issue with the latest version of admin-on-rest. Feel free to reopen if you can provide a code sample that fails.

**Closed by fzaninotto** 2016-12-21 13:40 UTC
