### ISSUE TITLE
MultiSelect Dropdown Input

### ISSUE THREAD

**Issue by mantis** [marmelab/admin-on-rest#476] opened 2017-03-19 09:23 UTC
For a long dropdown list, that could allow multiple values (e.g. when filtering) - it would be good to provide a multiselect drop down.

For instance, similar to the functionality in https://jedwatson.github.io/react-select/

Would you see this as a 3rd party component, or something the core should support?

**Comment by leesei** [comment] 2017-03-20 00:44
See #45

**Comment by fzaninotto** [comment] 2017-03-20 07:52
Duplicate of #45

**Closed by fzaninotto** 2017-03-20 07:52 UTC
