### ISSUE TITLE
[Feature] Put material-ui in peerDependency/optionalPeerDependency.

### ISSUE THREAD

**Issue by kopax** [marmelab/admin-on-rest#1082] opened 2017-09-23 23:45 UTC
## Issue Type

- [x] Feature (https://github.com/react-boilerplate/react-boilerplate/blob/master/.github/CONTRIBUTING.md#feature-requests)

## Description

I am reading at the documentation and I feel surprise in a good way by the `<Admin />` component that does a good part of configuration for us.

However for an application with needs of customization (many cases), people would rather go with the *Build your own App* way.

I greatly appreciate the depth of customization possibility by using only the thing you need.

All the UI components use material-ui, and in the documentation it is often said that if mui components are used, it will require a `<MuiThemeProvider />`.

This is why I would like to recon to remove `material-ui` from dependencies, and add it to optional/peerDependency.

By doing this `mui` UI component folder will be shown as an example and could even be it's own package `admin-on-rest-mui`. 
_(I use rollup do do ES6 package and I am following this [issue](https://github.com/marmelab/admin-on-rest/issues/1077) for using rollup with AOR)_

I am myself looking to a different [library](https://bootstrap-styled.kopaxgroup.com/) than material-ui.

Planing these change  will also reduce the whole `admin-on-rest` library size.

# Versions

- AOR: 1.3.1
- Node/NPM: 8.5.0/5.4.2

**Comment by fzaninotto** [comment] 2017-09-25 07:13
Duplicate of #32

**Closed by fzaninotto** 2017-09-25 07:13 UTC
