### ISSUE TITLE
Support for multiple APIs?

### ISSUE THREAD

**Issue by 0xMatt** [marmelab/admin-on-rest#943] opened 2017-08-17 17:04 UTC
Hello, asking here because I could not find the answer within the documentation. Does this library support interfacing with multiple apis and selecting which api will be used for a certain resource?

**Comment by djhi** [comment] 2017-08-17 18:50
Duplicate of #682. See this [answer](https://github.com/marmelab/admin-on-rest/issues/682#issuecomment-302864108) for a solution

**Closed by djhi** 2017-08-17 18:50 UTC
