### ISSUE TITLE
BooleanInput does not work in the nest field

### ISSUE THREAD

**Issue by datafibers** [marmelab/admin-on-rest#1328] opened 2017-12-21 16:53 UTC
```
<BooleanInput source="connectorConfig.choose_or_create" label="Choose/Create Topic?" style={{ width: 500 }} />
<BooleanInput source="test_flag" label="Stream Back the Result?" style={{ width: 500 }} />
```

I test it the value is show correctly in the normal json field. if it is nested, it always shows true

{ "test_flag":"false", "connectorConfig":{"choose_or_create":"false"}}
if I change BooleanInput  to TextInput, value shows correct

**Comment by fzaninotto** [comment] 2017-12-21 17:00
Can't reproduce either on `master` or `next`. Whci version of admin-on-rest are you using? Which version of `redux-form` is installed?

**Comment by datafibers** [comment] 2017-12-21 17:02
This happens in the edit view. 
for versions
    "admin-on-rest": "~1.3.2",
    "aor-dependent-input": "^1.2.0",
    "aor-language-chinese": "^1.0.3",
    "aor-language-french": "^1.8.0",
    "aor-rich-text-input": "^1.0.0",
    "material-ui": "~0.19.0",
    "prop-types": "~15.5.7",
    "react": "~15.5.4",
    "react-dom": "~15.5.4",
    "react-redux": "~5.0.4",
    "react-router-dom": "~4.1.0",
    "react-tap-event-plugin": "~2.0.1",
    "redux-form": "~7.0.3",
    "redux-saga": "~0.15.0"

**Comment by fzaninotto** [comment] 2017-12-21 17:05
Nothing strange here, so it's not a matter of dependency.

Can you try and reproduce a minimal app with that bug, based on a fork of the following CodeSandbox? 

https://codesandbox.io/s/ElxGNxBY0

**Comment by djhi** [comment] 2018-01-16 15:06
No news for some time, closing. Feel free to reopen if needed

**Closed by djhi** 2018-01-16 15:06 UTC
