### ISSUE TITLE
Allow AlwaysOn filters with default value

### ISSUE THREAD

**Issue by macrel** [marmelab/admin-on-rest#1740] opened 2018-04-12 10:31 UTC
First off, I love admin-on-rest! I created an awesome administrative portal for our REST API in no-time, so huge thanks to you guys!

I have one issue however I can't find a workaround for. I want to have this:

- A date filter that is always visiable (alwaysOn), so user don't have to click 'add filter' first
- The filter must have a default value (some date value, for example current date like this: new Date()
- The user must be able to change the filter value (that's why I use 'filters' and not the permanent 'filter' on the grid)

So, I created a a simple grid, showing a count for a certain subject with 2 date filters: 

`

    const GridFilters = (props) => (<Filter {...props}>

		<DateInput source="to_date" label="To date" alwaysOn options={{
				mode: "portrait",
				locale: "nl"
			}} />		
	
		<DateInput source="initialfilter_from_date" label="From date" defaultValue={props.date} alwaysOn options={{
				mode: "portrait",
				locale: 'nl',
				defaultDate: props.date,
			}} />					
    </Filter>);
    <List title="Dategrid" perPage={50} filters={<GridFilters date={new Date()} />} {...props}>
        <Datagrid >
           <TextField source="subject" />
           <NumberField source="count" />
	</Datagrid>
</List>`

My app has a custom menu with multiple pages. If I directly go to the url that this page is visible on (for example: http://localhost:3001/#/admin/dategrid , the default value is set in the input and applied in the filter. 

However, if I switch to another page in my menu and switch back to this page, the default filter is not set in the input nor in the filters sent to my API. In my custom restClient the params.filters are not filled. There are no errors in the console and if I press F5 the filter is set again.

Maybe needed info for reproduction info: the grid is added to my <Admin.. component as a resource ad passed to the 'list' property of a resources.

Ps. an additional bug I found with the DateInput is that setting a defaultValue like this: new Date() works, however, set a custom date like this: new Date(2018,1,1,0,0,0) doesn't work. Don't know why, but the filter does not get applied. I have worked around that by manually checking inputs fields with default values in my restClient and manually adding them to the querystring, but it doesn't work out of the box. This issue maybe better belongs in a seperate issue however since it seems not really related.

Thanks!

Ps. I use admin-on-rest 1.4.0 according to my package.json

**Comment by djhi** [comment] 2018-04-12 10:36
Thanks for the detailed report. Would you mind setting up a codesandbox to show this issue ? Besides, what version are you using ?

**Comment by macrel** [comment] 2018-04-12 11:33
Hi,

I have created a sandbox. I use admin-on-rest 1.4.0.

In the codesandbox you can see the issue of the emptied search inputs, however, the other issue I described does not occur in this sandbox. So forget about that.

Here's the sandbox: https://codesandbox.io/s/1oqyzknr03

- Once loaded you will see on the posts list the default search values
- Now click the comments menu
- Click back to posts (maybe repeat a few time)
- Search inputs default values are now empty

Hope this helps! Looking forward to your feedback. Thanks!

**Comment by macrel** [comment] 2018-04-12 11:44
Edit: I was actually able to reproduce both issues in the sandbox. So if you checkout the sandbox you can now see 2 issues:

1. The posts.js (Posts menu) has a default filter where the default value is initialized as a new Date(2018,1,1,0,0,0) for example. This date is NOT added as filter on inital page load. If you change this defaultValue to simply new Date() the date IS added as filter on intial page load.
2. Next, if you switch to the comments menu, you will see a default filter being added. Here it works because I simply used new Date() as default value, instead of new Date(2018,1,1,0,0,0). However, if you now switch back and forth between the 2 menus a couple times, you will see that also on this page the default values get lost.

**Comment by fzaninotto** [comment] 2018-04-13 12:48
So I can't reproduce the bug of the filter losing its default value in isolation (with just a date input with a default value in the post). the bug seems to come from having it in both the comment and the post list.

I can reproduce the bug of an alwaysOn filter with a default value not ending in the restClient query, whatever the input type (not only for date fields).

**Comment by fzaninotto** [comment] 2018-04-13 13:26
This is a truly hard problem.

## Solution 1

The naive way to implement this would be to iterate over every filter in the `<FilterForm>` constructor, to see which child has both `alwaysOn` and `defaultValue`, but does not appear in the `initialValues`. These children define a set of filters to pass to `setFilters`.

The problem with this approach is that the list will fetch the API twice, once when the List mounts, and one when the Filter mounts. The list will briefly appear unfiltered before being filtered. From a performance and usability standpoint, it's a no-go.

# Solution 2

We could also inspect the individual filters not in the `FilterForm` component, but in the `List` - soon enough to modify the initial fetch to the API. But the element passed as `filters` can be anything the user decides - not necessarily a `<Filter>`. Besides, we've already had bad experiences with inspecting children of children in the past. So that's also a no-go.

## Solution 3

We could explicitly forbid setting both `alwaysOn` and `defaultValue` in a filter form, and ask the user to pass these in a new prop, say `defaultValues`. The `List` could inspect this prop, and modify the initial fetch, without inspecting the filter form children.

I don't see any other possibility.

**Comment by macrel** [comment] 2018-04-13 15:54
Thanks for you reply and extensive information / research! I agree Solution 3 would be the only real solution here. Looking forward to see something like this in a next release.

**Comment by fzaninotto** [comment] 2018-04-16 08:49
Fixed by #1745

**Closed by fzaninotto** 2018-04-16 08:49 UTC
Labels: enhancement
