### ISSUE TITLE
How to create submenu in left navbar

### ISSUE THREAD

**Issue by kodmanyagha** [marmelab/admin-on-rest#446] opened 2017-03-15 06:53 UTC
I'm new in ReactJS and admin-on-rest. This is so good framework for creating gui fast. Thx for this. I want to create submenu in navbar. Is this possible, and how to make this. Thanks for your answer.

**Comment by fzaninotto** [comment] 2017-03-15 11:15
Hi, and welcome!

Because your Issue leads me to repeat myself:

- use StackOverflow for asking questions rather than GitHub Issues
- search for previous issues before creating a new one (yours is a duplicate of #435)

It motivated me to write [contributing guidelines](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md). Make sure you read them!

**Closed by fzaninotto** 2017-03-15 11:15 UTC

**Comment by az** [comment] 2017-03-15 11:25
@kodmanyagha 

update admin-on-rest to the newest version .. than use custom Menu component as described https://marmelab.com/blog/2017/03/10/admin-on-rest-0-9.html#custom-menu
at that moment that would be material-ui related question so please follow http://www.material-ui.com/#/components/menu "nested menus"
