### ISSUE TITLE
Example: How to add a create button with a ReferenceManyField

### ISSUE THREAD

**Issue by pbreah** [marmelab/admin-on-rest#1402] opened 2018-01-19 16:09 UTC
**What you were expecting:**

https://marmelab.com/admin-on-rest/Fields.html#referencemanyfield

 On the documentation I have the option to show a list of related fields using a ```<ReferenceManyField>``` which is great, and it works. But following the same documentation, wanting to hide the resource from the sidebar menu

> Note: You must add a ```<Resource>``` for the reference resource - admin-on-rest needs it to fetch the reference data. You can omit the list prop in this reference if you want to hide it in the sidebar menu.)

I'm also blocking my way from creating new rows on that resource, because there is no "Create" button when showing a list of related rows nested inside another resource (and hiding it from the sidebar menu)

**What happened instead:**
There is no create button, so there is no way to create rows on a nested resource.
![reference-many-field-datagrid](https://user-images.githubusercontent.com/191634/35159183-5a107258-fd07-11e7-8816-414e24615eb8.png)

I saw the pull request #744 but this is different since this is related to ```<ReferenceManyField>``` not ```<ReferenceArrayInput>```

**Steps to reproduce:**
Same snippet of code on the documentation:
```js
import React from 'react';
import { Edit, Datagrid, SimpleForm, DisabledInput, DateField, EditButton, ReferenceManyField, TextField, TextInput } from 'admin-on-rest';

export const PostEdit = (props) => (
    <Edit {...props}>
        <SimpleForm>
            <DisabledInput label="Id" source="id" />
            <TextInput source="title" />
            <ReferenceManyField label="Comments" reference="comments" target="post_id">
                <Datagrid>
                    <TextField source="body" />
                    <DateField source="created_at" />
                    <EditButton />
                </Datagrid>
            </ReferenceManyField>
        </SimpleForm>
    </Edit>
);
```

**Environment**

* Admin-on-rest version: 1.3.3
* Last version that did not exhibit the issue (if applicable): n/a
* React version: latest
* Browser: any

**Comment by djhi** [comment] 2018-01-19 16:12
Duplicate of #890 ?

**Comment by pbreah** [comment] 2018-01-19 16:28
I don't think so. On that issue he's referring to a pre-filled create resource form. This is just having a create button on a nested resource.

**Comment by djhi** [comment] 2018-02-16 17:07
This will be possible in 2.0. We'll add an example for this usecase. I renamed your issue accordingly

**Comment by djhi** [comment] 2018-02-20 07:47
Example: https://codesandbox.io/s/pp0o4x40p0

The relevant code parts are:
 
* the `CreateCommentButton` component inside `src/posts.js`
* the `CommentCreate` component inside `src/comments.js` (note how we set the `defaultValue` prop on `SimpleForm`)

**Closed by djhi** 2018-02-20 07:47 UTC
Labels: enhancement

**Comment by stephme** [comment] 2018-08-27 08:11
Broken link 😢

**Comment by djhi** [comment] 2018-08-27 08:16
Thanks for reporting, I updated the link

**Comment by stephme** [comment] 2018-08-27 09:07
Thx a lot @djhi

**Comment by djhi** [comment] 2018-08-27 15:38
There is a new section in the documentation with advanced tutorials. It does include one for this use case: https://marmelab.com/react-admin/AdvancedTutorials.html
