### ISSUE TITLE
ReferenceFields label hidden on the top of field

### ISSUE THREAD

**Issue by philippe-cleany** [marmelab/admin-on-rest#827] opened 2017-07-05 10:35 UTC
When use example on the repo, with the following commentShow component
I'm trying to use ReferenceField but the label is hidden 

```javascript
export const CommentShow = ({...props}) => (
  <Show {...props}>
    <SimpleShowLayout>
        <DateField source="created_at" />
        <ReferenceField source="post_id" reference="posts">
            <TextField source="title"/>
        </ReferenceField>
    </SimpleShowLayout>
  </Show>
);
```
As can be seen in the image, the ReferenceField label does not appear
 Whereas in th docs it is said that we can simply use label to show label on the top of the field
as default label should appear and label props only use if we want to change label name

![before](https://i.imgur.com/yd6z8Eb.png)

I will push patch in the coming hours to fix this, as default label is visible and we can just simply use 
 ```javascript
 addLabel={false} //to  hide it
``` 

![after](https://i.imgur.com/CoMD3fG.png)

**Comment by wesley6j** [comment] 2017-07-05 11:31
Maybe duplicate of #804 and solved in #812

**Comment by fzaninotto** [comment] 2017-07-05 12:46
Yep, that's a duplicate.

**Comment by philippe-cleany** [comment] 2017-07-05 13:04
Yes but fix it now, you don't have to pass `addLabel` to the `Referencefield ` ,  and you can use it just for hidding the label

**Comment by sebastien-cleany** [comment] 2017-07-05 14:11
@fzaninotto, indeed that a duplicate of #812, however #812 doesn't fix the issue. IMO the patch simply document a buggy behavior.

The default value of addLabel defined for ReferenceField is true, thus the default behavior without having "addLabel" set in prop should be to display the label. (and moreover this is the behavior of ReferenceManyField).

The buggy behavior is due to the use of redux on the component which initialized the component before the default props are set. And thus the default props are ignored for the component.

```javascript
ReferenceField.propTypes = {
    addLabel: PropTypes.bool,
    ...
};  

ReferenceField.defaultProps = {
    addLabel: true,
    ...
};
export default connect(mapStateToProps, {
    crudGetManyAccumulate: crudGetManyAccumulateAction,
})(ReferenceField);
```

IMHO The correct pattern would be, as in ReferenceManyField, to defined the default props on the component return by redux.

```javascript
ReferenceField.propTypes = {
    addLabel: PropTypes.bool,
    ...
};  

const ConnectedReferenceField = connect(mapStateToProps, {
    crudGetManyAccumulate: crudGetManyAccumulateAction,
})(ReferenceField);

ConnectedReferenceField.defaultProps = {
    addLabel: true,
    ...
};

export default ConnectedReferenceField;
```
Do you want us to PR a patch in this way ?

**Comment by fzaninotto** [comment] 2017-07-05 15:38
You're right, it's a bug. Please open a PR with the `ConnectedReferenceField` change, and undo the changes in #812.

**Closed** 2017-07-06 09:00 UTC
Labels: bug
