### ISSUE TITLE
Create a 'Reset filters' button

### ISSUE THREAD

**Issue by gandrin** [marmelab/admin-on-rest#816] opened 2017-07-03 07:27 UTC
Hello,

I have an issue with filters on the list page.
I'm using DateInput fields to create a "between" like filter. To manage display both input fields (From and To), I had to use the alwaysOn property.

However, I cannot empty the DateInput to reset the filters and display all my models.
A button reset filters would solve this by resetting the current chosen filters.

Thanks for your help.

**Comment by remi13131** [comment] 2017-07-03 13:47
Related : https://github.com/marmelab/admin-on-rest/issues/442

**Comment by fzaninotto** [comment] 2017-07-04 21:52
Duplicate of #817

**Closed by fzaninotto** 2017-07-04 21:52 UTC

**Comment by gandrin** [comment] 2017-07-05 13:56
@fzaninotto I won't consider it as a duplicate. Indeed the two issues are related with a common objective at first(the between filter). However, the features are different and this one can be used to clean all the filters with 1 click.

**Comment by fzaninotto** [comment] 2017-07-05 16:16
OK, it's not a duplicate.

But I don't want to implement this in the core - it will clutter the interface even more, unless a UX master shows me the contrary. 

You should be able to do that via a custom `<Filter>` component in userland, though.

**Comment by nickgrealy** [comment] 2020-11-26 02:06
Leaving this here for future travellers (myself included).

Extending upon the [custom `ListActions` toolbar example](https://marmelab.com/react-admin/List.html#actions)...

```js
import { FilterList } from "@material-ui/icons";
import React from "react";
import {
    Button,
    sanitizeListRestProps,
    TopToolbar
} from "react-admin";

const ListActionsTopToolbar = (props) => {
  const {
    className,
    exporter,
    filters,
    maxResults,
    setFilters,
    ...rest
  } = props;
  return (
    <TopToolbar className={className} {...sanitizeListRestProps(rest)}>
        
        {/* Clear Filters Button */}
      <Button onClick={() => setFilters({})} label="Clear Filters">
        <FilterList />
      </Button>

    </TopToolbar>
  );
};
```

**Comment by waynebloss** [comment] 2021-11-16 15:45
I don't understand not implementing an obvious feature just because it would clutter up the interface. It could easily be put into an overflow menu.

**Comment by djhi** [comment] 2021-11-16 15:57
Well, here's what I suggest: open a pull request implementing this button, with tests and screencasts/screenshots of the results. In the event we end up choosing to not include it, you will then be able to keep the code and open source it as an addon package.

**Comment by waynebloss** [comment] 2021-11-16 16:03
Thank you for your suggestion.

Here's what I suggest: Listen to your users and appreciate the feedback that they've taken the time to give to you.

**Comment by hiaselhans** [comment] 2022-08-11 08:12
i think this finally lands in 4.3 with #8017

**Comment by qpointsystems** [comment] 2023-05-21 19:32
Came here looking for others on same path. Happy to hear this finally made the cut, feature wise. Tricky UIX wise... but, as they say, where there is a will, there is a way ;)
