### ISSUE TITLE
Second order reference

### ISSUE THREAD

**Issue by leesei** [marmelab/admin-on-rest#422] opened 2017-03-11 14:24 UTC
Using JSONPlaceholder's example, this code can render the commentator's email in the Post List.
```jsx
export const PostList = (props) => (
    <List {...props} filters={<PostFilter />}>
        <Datagrid>
            <TextField source="id" />
            <ReferenceField label="User" source="userId" reference="users">
                <TextField source="name" />
            </ReferenceField>
            <TextField source="title" />
            <ReferenceManyField label="Comments" reference="comments" target="postId">
                <SingleFieldList>
                    <ChipField source="email" />
                </SingleFieldList>
            </ReferenceManyField>
            <EditButton />
        </Datagrid>
    </List>
);
```

How can I use the email to look up the commentator's name in User resource (assuming all commentators are users)?

**Comment by fzaninotto** [comment] 2017-03-11 22:37
Duplicate of #408

**Closed by fzaninotto** 2017-03-11 22:37 UTC

**Comment by leesei** [comment] 2017-03-16 06:43
I've written a component for this, though not exactly solves the case in the OP.
This is not general enough to be a built-in component like `<ReferenceManyField>` but I think it's worth putting into the documents.
I'll rework the code and use examples from JSONServer if the maintainers agree.

```
import React, { Component, PropTypes } from 'react';
import { connect } from 'react-redux';
import LinearProgress from 'material-ui/LinearProgress';
import {
  // `crudGetOneReference` uses `crudGetMany` and more performant (potentially)
  // also we have to disable `cancelPrevious` if using `crudGetOne`
  crudGetOneReference as crudGetOneReferenceAction
} from 'admin-on-rest';


/**
 * Schema for objects:
 *
 * @example
 *  district:
 *    type: object
 *    properties:
 *      id: int
 *      name: string
 *  street:
 *    type: object
 *    properties:
 *      id: int
 *      districtId: int
 *      name: string
 *
 * @example Under <StreeList>, we could <ReferenceField> to show both
 * *district* and *street* names
 * <ReferenceField label="District" source="districtId" reference="districts">
 *     <TextField source="name" />
 * </ReferenceField>
 * <TextField source="name" />
 *
 * On entity that links to street only (say a building), we can create a
 * Container Component that resolves the district internally:
 *
 * @example
 * <ReferenceField label="Street" source="streetId" reference="streets">
 *     <StreetField  />
 * </ReferenceField>
 */

class StreetField extends Component {
    componentDidMount() {
        const { crudGetOne, reference, record, source } = this.props;
        crudGetOne(reference, record[source]);
    }

    render() {
        const { record, data } = this.props;
        if (typeof data === 'undefined') {
            return <LinearProgress style={{ marginTop: '1em' }} />;
        }
        return (<span key={record.id}>{data.name} {record.name}</span>);
    }
}
StreetField.propTypes = {
    addLabel: PropTypes.bool,
    basePath: PropTypes.string.isRequired,
    crudGetOne: PropTypes.func.isRequired,
    label: PropTypes.string,
    record: PropTypes.object.isRequired,
    reference: PropTypes.string.isRequired,
    data: PropTypes.object,
    resource: PropTypes.string.isRequired,
    source: PropTypes.string.isRequired,
};

const mapStateToProps = (state, props) => {
    const { record, source, reference } = props;
    return {
        data: state.admin[reference].data[record[source]]
    };
};

const ConnectedStreetField = connect(mapStateToProps, {
    crudGetOne: crudGetOneReferenceAction,
})(StreetField);

ConnectedStreetField.defaultProps = {
    addLabel: true,
    label: 'Street',
    reference: 'district',
    source: 'districtId',
};

export default ConnectedStreetField;

```

**Comment by leesei** [comment] 2017-03-16 06:57
Is there a good way to do second order reference generally?
I'm thinking of passing a map of `source: resource` to a container component that helps fetch the references into record.

```
<ReferenceDeepField label="Street" source="streetId" reference="streets"
    resolves={"districtId": "district" } >
    // `/district/districtId` is fetched to `record.district`
</ReferenceDeepField>
```

**Comment by fzaninotto** [comment] 2017-03-16 15:35
Sorry, I don't understand the question, can you elaborate?

**Comment by leesei** [comment] 2017-03-16 15:40
The `<StreetField>` I implemented resolves one record from other resource, I'm thinking of making a generalized component that can resolve multiple source in a record.

```
resolves = {
  "districtId": "district",
  "key1": "resource1",
  "key2": "resource2",
}
<ReferenceDeepField label="Street" source="streetId" reference="streets"
    resolves={"districtId": "district" } >
    // record = {
    //    ...fields, // fields for street
    //    district, // record for `/district/districtId`
    //    resource1, // record for `/resource1/key1`
    //    resource2, // record for `/resource2/key2`
    // }
</ReferenceDeepField>
```
