### ISSUE TITLE
ImageInput accepts more then one image in single file upload

### ISSUE THREAD

**Issue by hamidfzm** [marmelab/admin-on-rest#966] opened 2017-08-23 15:45 UTC
Here is a sample code I use for image upload:
```jsx
                <ImageInput source="icon" label="Icon" accept="image/*" multiple={false}>
                    <ImageField source="src" />
                </ImageInput>
```
But I can put multiple images in this field like the screenshot below:
<img width="1091" alt="screen shot 1396-06-01 at 8 16 38 pm" src="https://user-images.githubusercontent.com/5591800/29625097-05bbe638-8840-11e7-8ac6-569432b7f788.png">

Setting `multiple={false}` only changes dragzone text and has no other effects.

- Admin-on-rest version is 1.2.1 
- React version is 15.6.1
- Browser is chrome

**Comment by djhi** [comment] 2017-08-23 15:56
Duplicate of #874. Fixed with #954. This will be released in the next minor version: `1.2.3`

**Closed by djhi** 2017-08-23 15:56 UTC
