### ISSUE TITLE
Rest-admin won't redirect to /login page when {(permissions) => {}} is passed as a child of <Admin /> instead of list of <Resource />

### ISSUE THREAD

**Issue by qstyler** [marmelab/admin-on-rest#1605] opened 2018-03-03 10:59 UTC
I expect my react-admin app to show me the login page when I'm not logged in yet. And when I have a function as the <Admin /> only child.

In fact I stuck with the Loading page saying “The page is loading, just a moment please.”.

![image](https://user-images.githubusercontent.com/5556580/36933526-7d7e4658-1eda-11e8-9187-38ae3d4fe371.png)

I tried to reproduce it on a clean install taken from the Tutorial and got the same result.

```JSX
// in src/App.js
import React from 'react';
import { Admin, Resource } from 'react-admin';
import jsonServerProvider from 'ra-data-json-server';
import authProvider from './authProvider';

import { PostList } from './posts';
import Dashboard from './Dashboard';

const App = () => (
    <Admin
      dataProvider={jsonServerProvider('http://jsonplaceholder.typicode.com')}
      dashboard={Dashboard}
      authProvider={authProvider}
    >{(auth)=>
        <Resource name="posts" list={PostList} />
     }
    </Admin>
);

export default App;
```

Auth provider here is also a provider [taken from the tutorial](https://github.com/marmelab/admin-on-rest/blob/next/docs/Tutorial.md#adding-a-login-page).

**Environment**

* Admin-on-rest version: react-admin: ^2.0.0-beta2
* React version: 16.2.0
* Browser: Chrome 64.0.3282.186

**Comment by afilp** [comment] 2018-03-03 20:03
I've also experienced this "sometimes". "Sometimes" means that I am not sure when this happens, most likely when the "token" has expired while I am still "loggedin"? I only noticed this when I re-opened a Firefox that had it closed for many days.

Version: "next"

**Comment by 102** [comment] 2018-03-05 08:45
I've encountered this behavior when filtered all resources to the empty array, i.e. these code snippets could probably result in same way?

```js
// in src/App.js
import React from 'react';
import { Admin, Resource } from 'react-admin';
import jsonServerProvider from 'ra-data-json-server';
import authProvider from './authProvider';

import { PostList } from './posts';
import Dashboard from './Dashboard';

const App = () => (
    <Admin
      dataProvider={jsonServerProvider('http://jsonplaceholder.typicode.com')}
      dashboard={Dashboard}
      authProvider={authProvider}
    >
     {(auth)=>[]}
    </Admin>
);

export default App;
```

or

```js
// in src/App.js
import React from 'react';
import { Admin, Resource } from 'react-admin';
import jsonServerProvider from 'ra-data-json-server';
import authProvider from './authProvider';

import { PostList } from './posts';
import Dashboard from './Dashboard';

const App = () => (
    <Admin
      dataProvider={jsonServerProvider('http://jsonplaceholder.typicode.com')}
      dashboard={Dashboard}
      authProvider={authProvider}
    >
     {[]}
    </Admin>
);

export default App;
```

**Comment by afilp** [comment] 2018-03-09 08:52
*UPDATE:* It happens in all browsers (while developing at least) that I tested: Chrome, Firefox, IE, provided that you *clear the browsing history (cache)*.

@djhi This is a serious issue (we cannot develop anymore), have you experienced this? If you could guide us where to look for a fix it would be appreciated. Thank you.

**Comment by codergr** [comment] 2018-03-09 11:24
+1 from my side have same issues and have tested it in multiple environments.

**Comment by afilp** [comment] 2018-03-09 12:59
Not sure if this helps, but for some reason the app works on a "non-clean" Chrome, i.e. the one I am using every day without any "Clear Browser Data" on that Chrome for months (no need). I am afraid to do so, as I will not be able to work anymore with react-admin. in Incognito mode the app does not work, which shows that the "default" when using "permissions" (maybe) is to stay at "Loading...".

What may be *cached* on my main Chrome that makes it work? This is strange.

**Comment by 102** [comment] 2018-03-09 19:15
> What may be cached on my main Chrome that makes it work? This is strange.

It's probably something, that distinguishes authenticated and unauthenticated user? I managed to workaround this bug just by avoiding any possibility of `<Admin />` without any `<Resource />`

**Comment by afilp** [comment] 2018-03-09 19:22
@102 Thanks for the info! What should we do to avoid this, I am not sure what you mean.

**Comment by tkvw** [comment] 2018-03-09 19:33
Looks like it works in sandbox: https://codesandbox.io/s/0y4pqp3nwn

**Comment by afilp** [comment] 2018-03-09 19:43
@tkvw It still puzzles me, exactly the same URL, one is Google Incongnito (not working), the other is Firefox (now works):

![image](https://user-images.githubusercontent.com/7850073/37226443-9f32b272-23e2-11e8-952a-43f235bf179e.png)

**Comment by tkvw** [comment] 2018-03-09 19:51
Works here
![image](https://user-images.githubusercontent.com/621098/37226851-935b5d0c-23db-11e8-8ff1-a50655a27e83.png)

Are you behind a proxy? Try restarting your computer first.

**Comment by afilp** [comment] 2018-03-09 19:59
I refreshed the dependency and it worked indeed.

In my case, I use BETA-3 which is released. This says BETA-2 though, is there any BETA-3 sandbox available?

![image](https://user-images.githubusercontent.com/7850073/37226961-4947e1fa-23e4-11e8-8b11-adc364111590.png)

**Comment by tkvw** [comment] 2018-03-09 20:04
So, you can simply fork the sandbox and update the dependencies, nothing special about it. Just click add and enter `react-admin@2.0.0-beta3`

**Comment by afilp** [comment] 2018-03-09 20:47
Indeed, I did this and it works. I have to figure out what may the culprit be. FYI, I use 'aor-loopback'.

**Comment by afilp** [comment] 2018-03-09 22:26
I think I narrowed down where the problem is:

https://github.com/marmelab/admin-on-rest/blob/73414972c9b62207ccc64f429d1a96b9b13d8c70/packages/ra-core/src/CoreAdminRouter.js#L27

The problem starts when there is no `token` in localStorage (I thought of this due to the "clean" vs "non-clean" browser data case):

```
if (type === AUTH_GET_PERMISSIONS) {
        const token = localStorage.getItem('token');
        if (!token) {
            return Promise.reject();
        }
        const role = localStorage.getItem('role');
        Promise.resolve(role);
    }
```

With no token, the `authClient` rejects. 

By rejecting, we then go to this line:
https://github.com/marmelab/admin-on-rest/blob/73414972c9b62207ccc64f429d1a96b9b13d8c70/packages/ra-core/src/CoreAdminRouter.js#L51

Which brings us to this "dreaded" "Loading..." deadlock:
https://github.com/marmelab/admin-on-rest/blob/73414972c9b62207ccc64f429d1a96b9b13d8c70/packages/ra-core/src/CoreAdminRouter.js#L99

If this is a simple change and someone knows, please let us know to add it to our code and test further.

Thanks!

**Comment by codergr** [comment] 2018-03-09 23:01
I overcome it temporarily in my setup by commenting those lines in 98 - 100 of  admin-on-rest/packages/ra-core/src/CoreAdminRouter.js. 

`      //if (!childrenToRender || childrenToRender.length === 0) {
        //    return <Route path="/" key="loading" component={loading} />;
        //}
`

Ugly hack and not acceptable I agree. Perhaps we could use this thread to think about the possible scenarios, in my opinion because there are no children to show the loading is not correct. Perhaps we should have different messages for different error cases. 

1. Loading -> when data are retrieved . list is populated
2. Data are empty -> popup a warning dialog informing the user
3. Token 

etc

**Comment by fzaninotto** [comment] 2018-03-10 21:17
My understanding is that there is no bug: if your `authProvider` rejects the promise, then there can't be any Resource, and the admin can't do anything. It's your job not to reject the promise at that point. 

Or am I missing something?

**Comment by codergr** [comment] 2018-03-10 21:52
I don't know :-) but my 2cents perhaps could popup an error instead of entering on a loop ? If I understand the code correctly one potential reason for this could also  happen on this error catch. Correct? @fzaninotto you know better its your baby :-)

https://github.com/marmelab/admin-on-rest/blob/73414972c9b62207ccc64f429d1a96b9b13d8c70/packages/ra-core/src/CoreAdminRouter.js#L50

**Comment by fzaninotto** [comment] 2018-03-10 22:21
I agree: if we `catch`, we should set the `children` to another value than loading, and it should show an error.

https://github.com/marmelab/admin-on-rest/blob/73414972c9b62207ccc64f429d1a96b9b13d8c70/packages/ra-core/src/CoreAdminRouter.js#L50-L52

**Comment by afilp** [comment] 2018-03-10 22:39
As @fzaninotto mentioned, I changed the `authProvider` code to...

```
        if (type === 'AUTH_GET_PERMISSIONS') {
            const role = storage.load('role');
            return Promise.resolve(role);
        }
```
...and it worked.

Please note that the problem was in the related documentation of `next`, see here:

https://github.com/marmelab/admin-on-rest/blob/73414972c9b62207ccc64f429d1a96b9b13d8c70/docs/Authorization.md#configuring-the-auth-client

@fzaninotto 
1. Do we really *not* need to check for the `token` (i.e. if the user is loggedin?). May I assume that you check for that immediately after, in order to redirect the user to the login?
2. If yes, I can update the DOC with the above code. Do you want me to do this?

Thanks.

**Comment by fzaninotto** [comment] 2018-03-14 12:23
No, the doc is correct, but the react-admin code should behave differently when the `authProvider` throws. It should log the user out. I'll open a PR for that.

**Comment by fzaninotto** [comment] 2018-03-14 15:10
Fixed by #1650

**Closed by fzaninotto** 2018-03-14 15:10 UTC
Labels: bug

**Comment by prakhar2407** [comment] 2023-03-08 11:28
@fzaninotto This still exits, now it no longer shows the loading but it shows a navbar with name of the user as null

**Comment by fzaninotto** [comment] 2023-03-08 12:51
@prakhar2407 Thanks for the feedback. Can you please open a new issue with a reproduction case?
