### ISSUE TITLE
Add ReferenceManyInput field

### ISSUE THREAD

**Issue by fnberta** [marmelab/admin-on-rest#45] opened 2016-09-26 16:14 UTC
What are your plans regarding a ReferenceManyInput field (like it was available in ng-admin)? I guess this depends on a suitable ui component landing in material-ui. https://github.com/TeamWertarbyte/material-ui-chip-input looks really nice, would you be open for a component based on that? I could give it a spin.

**Comment by fzaninotto** [comment] 2016-10-03 21:28
We have plans to make admin-on-rest as awesome as ng-admin. No, even more. 

But it will take months. We need all the help you can give.

The chip input seems OK for an array value, but for references you need autocomplete. I don't see anything of acceptable quality in material UI land, do you have other ideas?

I'm closing this one as we won't open one issue for every ng-admin feature that needs to be ported. Feel free to continue the discussion about the implementation even though the issue is closed.

**Comment by fnberta** [comment] 2016-10-04 11:34
This chip input component actually supports autocomplete. If you go to the [demo storybook](https://teamwertarbyte.github.io/material-ui-chip-input/) and select "with floating label and hint text", you actually get a similar experience to what is now in ng-admin. I hope I'll find the time this week to take a closer look.

**Comment by fzaninotto** [comment] 2016-10-11 14:02
Reopening this one as it'll guide us for future enhancements.

**Comment by leesei** [comment] 2017-03-16 07:14
Alas, I need this one also.
Guess that'll be another PR :tada: .

**Comment by kimkha** [comment] 2017-03-16 07:31
@fzaninotto Can I add [material-ui-chip-input](https://github.com/TeamWertarbyte/material-ui-chip-input) to aor dependencies and make PR? I'm happy to help, but I wonder what is the true way to do that kind of thing.

**Comment by fzaninotto** [comment] 2017-03-16 08:34
@kimkha Yes, it's a small dependency, no problem. Could you and @leesei coordinate efforts?

**Comment by leesei** [comment] 2017-03-16 09:01
@kimkha I haven't started on it yet but I'll implement it before mid-April.
Are you free to start it now?

**Comment by kimkha** [comment] 2017-03-16 09:14
I'm OK to start now, but I think it take time to start, because I'm new with AOR :)

Which function should we support? Array values, reference to many,... what's more?

**Comment by leesei** [comment] 2017-03-16 09:32
I suppose `<ReferenceManyInput>` will bind to a array of ids to `source`.
I'm not sure if we need a `<SelectManyInpu>t`/`<MultiSelectInput>`

**Comment by kimkha** [comment] 2017-03-16 09:46
Currently, we have `<ReferenceManyField>`. I think we must separate to 2 inputs: `< ReferenceManyInput>` for reference, and `<MultiSelectInput>` for array only. Because they look like difference...

The first thing, we must handle API calling, and when user choose one, we need to insert the ID of item. But in case of second one, we just only insert the text.

**Comment by kimkha** [comment] 2017-03-18 06:10
I change my mind. I think we should re-use `<ReferenceInput>`, but its children is `<ArrayInput>`. That might be easy to implement and make AOR better reusable.

**Comment by kimkha** [comment] 2017-03-19 00:38
@fzaninotto What do you think about that idea? If yes, I need to change `<ReferenceInput>` in `fetchReferenceAndOptions` to add `crudGetMany`...

**Comment by fzaninotto** [comment] 2017-03-20 07:57
I think we should NOT reuse `<ReferenceInput>`, because that would add too many `if`s to the code, and make its API confusing. Instead, create a `<ReferenceManyInput>` and a `<SelectManyInput>`.

**Comment by kimkha** [comment] 2017-03-20 15:22
DONE. I will make PR.

**Comment by faviouz** [comment] 2017-05-28 22:08
This should be closed, the change has been merged for a while now

**Comment by fzaninotto** [comment] 2017-05-29 12:47
Right, fixed in #597

**Closed by fzaninotto** 2017-05-29 12:47 UTC
Labels: enhancement
