### ISSUE TITLE
Multiple ReferenceManyField on same resource with different filter

### ISSUE THREAD

**Issue by natrim** [marmelab/admin-on-rest#1068] opened 2017-09-22 07:02 UTC
When using multiple ReferenceManyField on same resource with different filter.

The Field is the filled only by the last query and not each respective queries.

Seems to have something to do with how the resources are fetched and cached.

example from the doc with filter:

```
<Edit {...props}>
        <SimpleForm>
            <DisabledInput label="Id" source="id" />
            <TextInput source="title" />
            <ReferenceManyField label="Inactive Comments" filter={{active: true}} reference="comments" target="post_id">
                <Datagrid>
                    <TextField source="body" />
                    <DateField source="created_at" />
                    <EditButton />
                </Datagrid>
            </ReferenceManyField>
            <ReferenceManyField label="Active Comments" filter={{active: false}} reference="comments" target="post_id">
                <Datagrid>
                    <TextField source="body" />
                    <DateField source="created_at" />
                    <EditButton />
                </Datagrid>
            </ReferenceManyField>
        </SimpleForm>
    </Edit>
```
it happens even if they are in different tabs in TabbedForm

**Comment by djhi** [comment] 2017-09-22 07:09
Duplicate of #1011 ?

**Comment by natrim** [comment] 2017-09-22 07:10
in #1011 he uses different references so no idea if it the same problem

**Comment by djhi** [comment] 2017-09-22 07:15
Symptom is the same. I'm quite sure it's the same prb

**Comment by ThieryMichel** [comment] 2017-09-28 16:37
The problem is not the same, reopening.

**Closed** 2017-09-29 08:48 UTC
