### ISSUE TITLE
Edit page not showing anything on refresh

### ISSUE THREAD

**Issue by RWOverdijk** [marmelab/admin-on-rest#981] opened 2017-08-28 10:32 UTC
When directly going to an edit page (http://localhost:3000/#/profiles/4 in my case) I'm seeing an empty container:

<img width="867" alt="screenshot 2017-08-28 12 31 26" src="https://user-images.githubusercontent.com/781745/29769974-f42ef792-8bec-11e7-8bff-a4882733eeda.png">

It _does_ work when I go to the edit page through the list view.

I have a custom rest client, but I assume it uses the same call as when clicking on edit in the list.

Any ideas?

**Comment by fzaninotto** [comment] 2017-08-28 12:23
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by RWOverdijk** [comment] 2017-08-28 12:24
@fzaninotto It's not a "how to" question. It's a "this is broken" issue. Bug. Please reopen.

**Closed by fzaninotto** 2017-08-28 12:23 UTC

**Comment by RWOverdijk** [comment] 2017-08-28 12:30
@fzaninotto Do you want me to rephrase it? If so, how? The data is there. I've checked. I'm pretty certain this is a bug as everything is default, and find_one is called as intended.

Frankly I think it's a bit problematic that you just close this issue without at least some additional information as to _why_ you think this belongs on stackoverflow.

**Comment by fzaninotto** [comment] 2017-08-28 12:32
If I can't reproduce it on the demo on the master branch, it means it's not broken.

**Comment by fzaninotto** [comment] 2017-08-28 12:34
or, to put it otherwise, to make us consider it as a bug, please provide a minimal test case based on the demo.

**Comment by RWOverdijk** [comment] 2017-08-28 12:36
@fzaninotto I'll try to create a test case.

Please consider adding that to your reply next time, I think it's friendlier that way 😄

**Comment by fzaninotto** [comment] 2017-08-28 12:42
Please consider reading the [contributions guidelines](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md) next time you open an issue, as the prominent yellow label invites you to 🙈 

I'm sorry if my tone sounds harsh. It turns out that 70% of the issues opened here are not problems about the aor code, but problems about users' code. We've chosen to offload the support to the community to focus on fixing real bugs, and add features that make aor better.

Sometimes we may close a genuine bug by mistake. I apologize in advance if it's your case. But you'll have to prove it first.

**Comment by RWOverdijk** [comment] 2017-08-28 12:44
> A code example or link to a repo, gist or running site. (hint: fork this sandbox to create a reproducible version of your bug)

You're absolutely right. I apologize. :)

**Comment by RWOverdijk** [comment] 2017-08-28 15:17
@fzaninotto I found the reason for the breakage. It was my code, but I think it's also a bug. I can't share my code because of the API you'd have to use, but I'm sure my explanation is clear enough:

It looks like the List screen passes the details of the selected (EditButton) item to the Edit page. BUT it also performs a GET request for the GET_ONE action. **The problem** is, that the response can be bogus (I tested it by setting the data in my restClient to `return {data: {swag: true}};`), but the edit page will remain populated. It won't show an error, throw an exception, show a notification or even clear out the fields. It just _stays_. Which means, when you directly access the edit screen, the data will not be available, because it didn't get it from the list this time.

So, I'd say that the way it works is _good_. But it should throw an error if the data returned from a request is invalid.


```js
  const convertHTTPResponseToREST = (response, type, resource, params) => {
    const {json} = response;

    let key = Object.keys(json)[0];

    switch (type) {
      case GET_LIST:
        return {
          data : json[key].map(x => x),
          total: response.headers.get('X-Total-Count') || 1,
        };
      case CREATE:
        return {data: {...params.data, id: json[key].id}};
      default:
        // This is completely fine for the edit page. And it will keep working. That's wrong.
        return {data: {swag: true}};
    }
  };
```

The cause of this, for me, is that we have a very weird, nested response. That's why I'm using `let key = Object.keys(json)[0];`. The bug for me was that last line of code, which had to be `return {data: json[key]};` instead of `return {data: json};`.

A lot of information, but I hope it makes sense. Do you agree this should throw an error?

**Comment by fzaninotto** [comment] 2017-09-12 09:40
Yep, you're right. Do you mind opening a new issue explaining the use case and the need for an error message?

**Comment by RWOverdijk** [comment] 2017-09-14 08:56
Will do :)

**Comment by llioor** [comment] 2017-12-17 14:29
@RWOverdijk @fzaninotto Hi guys.. I have the same issue as described here: https://github.com/marmelab/admin-on-rest/issues/981#issuecomment-325383495
@RWOverdijk what is the new case for it?
