### ISSUE TITLE
0.9.2 design break 

### ISSUE THREAD

**Issue by remi13131** [marmelab/admin-on-rest#485] opened 2017-03-20 16:18 UTC
Hi !
With the exact same code, upgrading [ EDIT: from 0.9.1 ] to 0.9.2 breaks the Datagrid when there is an important nuimber of columns. In smaller tables, it renders fine.

Before Upgrade : 
![before-0 9 2-upgrade](https://cloud.githubusercontent.com/assets/11832241/24109524/29112ad2-0d91-11e7-9fb1-df6d7e8aa3e3.jpg)

After Upgrade : 
![after-0 9 2-upgrade](https://cloud.githubusercontent.com/assets/11832241/24109558/49c7576a-0d91-11e7-8a39-86acb633d3dd.jpg)
(Pagination buttons, edit and delete are still here if I dezoom, but they are hidden on the right. There isn't even a horizontal scrollbar to get there)

**Comment by fzaninotto** [comment] 2017-03-20 16:34
Which version did you upgrade from? I less than 0.9, it may be a duplicate of #434

**Comment by remi13131** [comment] 2017-03-20 16:38
Oh yes sorry I forgot to mention, I upgraded from 0.9.1

**Comment by fzaninotto** [comment] 2017-03-20 16:45
OK. It's very weird, and I can't reproduce any regression like this with my projects. Just to confirm the bug cause, can you try to remove the custom style applied to the div with prop `data-reactroot` and check if that fixes the problem?

![image](https://cloud.githubusercontent.com/assets/99944/24110894/fdb4cdc2-0d94-11e7-9dd1-28cfbad99a3a.png)

**Comment by remi13131** [comment] 2017-03-20 16:58
as you can see, nothing funky in the Datagrid definition, same issue in Chromium and FF, and removing custom style for data reactroot changes nothing :/ 

![0 9 2-design-bug](https://cloud.githubusercontent.com/assets/11832241/24111395/914d2308-0d96-11e7-9504-f511c45a1c19.jpg)
![Uploading 0.9.2-FF-no-custom-style-bug.jpg…]()

**Comment by fzaninotto** [comment] 2017-03-20 17:06
Maybe the issue is with filters. I see your filters are all `alwaysOn`. What happens when you reove some of them?

**Comment by mantis** [comment] 2017-03-20 20:05
@fzaninotto @remi13131  Hi Remi :) - I can reproduce this between 0.9.1 and 0.9.2 and in my case, haven't done any custom styles. Interestingly it's also seems to be browser specific - Microsoft Edge seems to be fine. Google chrome Breaks. I can see Remi is using Firefox.

In my case, i've not done any custom css - only css i've used either comes from the demo app, or from the AOR itself. However, it first seems to break when the length of the filters exceed the size of the browser screen.

Note: I've also got the below going on in Edge (which may or may not be related) before the filters reach the full width of the screen. 
![image](https://cloud.githubusercontent.com/assets/16276382/24119228/5b9d8088-0da8-11e7-8a6f-5b76202508fa.png)

**Comment by fzaninotto** [comment] 2017-03-20 20:53
I can reproduce this with many filters.

**Closed** 2017-03-21 09:21 UTC
Labels: bug
