### ISSUE TITLE
Closable menu on mobile

### ISSUE THREAD

**Issue by kwiky** [marmelab/admin-on-rest#287] opened 2017-02-06 13:17 UTC
Please make the menu closable. It can be useful on mobile device.
![screenshot_20170206-141101](https://cloud.githubusercontent.com/assets/412969/22648297/41edb962-ec76-11e6-8e2d-7b6cccc452ba.jpg)

**Comment by fzaninotto** [comment] 2017-02-06 13:25
duplicate of #258

**Closed by fzaninotto** 2017-02-06 13:25 UTC
