### ISSUE TITLE
"Warning" when create  <SimpleForm/> with  ImageInput

### ISSUE THREAD

**Issue by whoait** [marmelab/admin-on-rest#1261] opened 2017-12-05 08:07 UTC
I create SimpleForm with ImageInput.

I followed the instructions in the document:
https://marmelab.com/admin-on-rest/Inputs.html#imageinput

This is my code:

```
export const PostCreate = (props) => (
    <Create actions={<PostCreateEditActions/>} {...props}>
        <SimpleForm toolbar={<PostCreateEditToolbar/>} defaultValue={postCreateDefaultValue}>        
            <ImageInput source="pictures" label="画像" accept="image/*" >
                <ImageField source="src"/>
            </ImageInput>
        </SimpleForm>
    </Create>
);
```
But when the console logs error:
bundle.js:4903 Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.

Check the render method of `TextField`.
    in getContext(ImageInput) (created by TextField)
    in div (created by TextField)
    in TextField (created by Labeled)
    in Labeled (created by ConnectedField)
    in ConnectedField (created by Connect(ConnectedField))
    in Connect(ConnectedField) (created by Field)
    in Field (created by FormFieldComponent)
    in FormFieldComponent (created by FormField)
    in FormField (created by FormInput)
    in div (created by FormInput)
    in FormInput (created by SimpleForm)
    in div (created by SimpleForm)
    in form (created by SimpleForm)
    in SimpleForm (created by Form(SimpleForm))
    in Form(SimpleForm) (created by Connect(Form(SimpleForm)))
    in Connect(Form(SimpleForm)) (created by ReduxForm)
    in ReduxForm (created by Connect(ReduxForm))
    in Connect(ReduxForm) (created by PostCreate)
    in div (created by Card)
    in div (created by Paper)
    in Paper (created by Card)
    in Card (created by Create)
    in div (created by Create)
    in Create (created by WithPermissionsFilteredChildren)
    in WithPermissionsFilteredChildren (created by getContext(WithPermissionsFilteredChildren))
    in getContext(WithPermissionsFilteredChildren) (created by getContext(getContext(WithPermissionsFilteredChildren)))
    in getContext(getContext(WithPermissionsFilteredChildren)) (created by Connect(getContext(getContext(WithPermissionsFilteredChildren))))
    in Connect(getContext(getContext(WithPermissionsFilteredChildren))) (created by PostCreate)
    in PostCreate (created by Route)
    in Restricted (created by Connect(Restricted))
    in Connect(Restricted) (created by Route)
    in Route (created by CrudRoute)
    in Switch (created by CrudRoute)
    in CrudRoute (created by Route)
    in Route (created by AdminRoutes)
    in Switch (created by AdminRoutes)
    in AdminRoutes (created by Connect(AdminRoutes))
    in Connect(AdminRoutes) (created by getContext(Connect(AdminRoutes)))
    in getContext(Connect(AdminRoutes)) (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in MuiThemeProvider (created by Layout)
    in Layout (created by WithWidth)
    in EventListener (created by WithWidth)
    in WithWidth (created by Connect(WithWidth))
    in Connect(WithWidth) (created by Route)
    in Route (created by Admin)
    in Switch (created by Admin)
    in div (created by Admin)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by Admin)
    in TranslationProvider (created by withContext(TranslationProvider))
    in withContext(TranslationProvider) (created by Connect(withContext(TranslationProvider)))
    in Connect(withContext(TranslationProvider)) (created by Admin)
    in Provider (created by Admin)
    in Admin (created by withContext(Admin))
    in withContext(Admin) (created by IndexNotification)
    in IndexNotification
printWarning @ bundle.js:4903
warning @ bundle.js:4927
mountIndeterminateComponent @ bundle.js:57473
beginWork @ bundle.js:57623
performUnitOfWork @ bundle.js:59626
workLoop @ bundle.js:59690
callCallback @ bundle.js:49944
invokeGuardedCallbackDev @ bundle.js:49983
invokeGuardedCallback @ bundle.js:49840
renderRoot @ bundle.js:59768
performWorkOnRoot @ bundle.js:60416
performWork @ bundle.js:60369
requestWork @ bundle.js:60280
scheduleWorkImpl @ bundle.js:60134
scheduleWork @ bundle.js:60091
scheduleTopLevelUpdate @ bundle.js:60595
updateContainer @ bundle.js:60633
(anonymous) @ bundle.js:64628
unbatchedUpdates @ bundle.js:60504
renderSubtreeIntoContainer @ bundle.js:64627
render @ bundle.js:64692
Object.defineProperty.value @ bundle.js:34475
__webpack_require__ @ bundle.js:20
(anonymous) @ bundle.js:63
(anonymous) @ bundle.js:66

Could you explain the cause of the error?

**Comment by fzaninotto** [comment] 2017-12-05 08:50
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Comment by llioor** [comment] 2017-12-27 19:20
@fzaninotto Hi, it is not an "How to" question. I have the same error and I found this case and nothing on Stackoverflow...
This what I found related to this issue, maybe it can help;

> The warning itself is legitimate. It points out a real problem that should be fixed either in your app or a library you use. You should not be trying to pass a ref to a functional component since it won't work. React now warns you about this.

**Comment by fzaninotto** [comment] 2018-01-04 12:48
I can't reproduce the error with your example code. Would you mind forking the following CodeSandbox to try and reproduce it online?

https://codesandbox.io/s/ElxGNxBY0

**Comment by samhiddenhand** [comment] 2018-01-04 19:09
I'm having the exact some bug with ImageInput using the official documentation's example code... hmm.

**Comment by samhiddenhand** [comment] 2018-01-04 19:21
Based on what I'm reading here, TextField needs to be rewritten as a class for this to work: https://github.com/react-dnd/react-dnd/issues/904

**Comment by fzaninotto** [comment] 2018-01-05 16:57
Again, I can't reproduce. Please provide a failing test case or a Codesandbox.

**Comment by yoshz** [comment] 2018-01-14 11:29
Same problem here, probably related to React 16.

**Comment by jyash97** [comment] 2018-01-22 16:47
@fzaninotto  I am facing the same issue with ImageInput and I searched across React issues I got one issue related to [this error](https://github.com/facebook/react/issues/10831). 

I tried to change the stateless component to Class Component but this didn't work well for me and the issue persisted and the link you have given in the above comments is using React 15 and this problem is coming in v16 as per I know.

**Comment by dimitrovs** [comment] 2018-01-23 03:27
@fzaninotto I have updated your sandbox https://codesandbox.io/s/lr75p4wx0l and now you can see the issue by clicking on any item. According to Dan Abramov in the thread linked above this is not a change of behavior in React 16, but just showing a warning for the first time, it is a bug in the component and not an issue caused by the new React version.

**Closed** 2018-01-30 15:17 UTC
Labels: bug

**Comment by dnsorlov** [comment] 2018-06-20 22:52
In my case 
> Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail.
appears only in production (react 16.2)
