### ISSUE TITLE
Error when using non-alpha numeric IDs on ReferenceField

### ISSUE THREAD

**Issue by TheBlusky** [marmelab/admin-on-rest#166] opened 2016-11-23 19:41 UTC
I'm using admin-on-rest for my new dashboard :-) Thanks Marmelab for this !

However, got a problem with "ReferenceField". I got the following error in my console :

![2016-11-23_20-37-00_firefox](https://cloud.githubusercontent.com/assets/441709/20576124/d025a5fe-b1bc-11e6-873b-0f830bda63a7.png)

For more context, I think it my be because I'm using String (UUID) as object identifier.
It's working well on simple List view, but when it's used in a ReferenceField, it's not working.

Strange behavior: if referenced objects are already in the cache (it may be already seen in another List view), it's working well.

Any idea ?

**Comment by arantes555** [comment] 2016-12-06 18:26
Seeing the same problem here

**Comment by fzaninotto** [comment] 2016-12-21 13:21
I can't reproduce the issue. I managed to use a jsonServer-powered API based on a dataset where each record is identified by a string.

Perhaps it's because your restClient doesn't handle string identifiers? Which restClient are you using? 

Also, which version of admin-on-rest are you using?

**Comment by fzaninotto** [comment] 2017-01-05 07:44
No news for some time, closing. Feel free to reopen if you can provide a failing test case.

**Closed by fzaninotto** 2017-01-05 07:44 UTC
