### ISSUE TITLE
When v2.0.0 will available for production use

### ISSUE THREAD

**Issue by kakoli4109** [marmelab/admin-on-rest#1259] opened 2017-12-05 05:57 UTC
At first, I want to give a lot of thanks to all the maintainer and contributor. This helps me a lot to complete our next project within a short timeline.

I used admin-on-rest v1.3.2 in my project and now we are ready for delivery, but we looking for v2.0.0 so that our dependencies are up to date.

So can anyone tell what is the planned roadmap for v2,0.0.

Thanks and Regards,
Kakoli

**Comment by fzaninotto** [comment] 2017-12-05 05:59
Duplicate of #1253

**Closed by fzaninotto** 2017-12-05 05:59 UTC
