### ISSUE TITLE
List view overflows page when multiple filters selected

### ISSUE THREAD

**Issue by petermullins** [marmelab/admin-on-rest#565] opened 2017-04-12 03:12 UTC
List filters don't wrap, so as you select more of them, the whole list grows horizontally until you can't see the list actions.  There's also no scrollbar, so you can't get to them at all without deselecting a filter.

E.g. from https://marmelab.com/admin-on-rest-demo/#/commands

![screen shot 2017-04-12 at 3 07 14 pm](https://cloud.githubusercontent.com/assets/16692130/24939528/284a24c4-1f92-11e7-83c5-b935fd1c08d5.png)

Observed in Chrome 57.0.2987.133 on Mac

**Comment by fzaninotto** [comment] 2017-04-12 06:37
Duplicate of #485, fixed by #488

**Closed by fzaninotto** 2017-04-12 06:37 UTC
