### ISSUE TITLE
Do you plan to bring in layout support as you've done in https://marmelab.com/ng-admin-demo/index.html#/dashboard

### ISSUE THREAD

**Issue by udy** [marmelab/admin-on-rest#1038] opened 2017-09-16 04:31 UTC
Particularly, Looking for 

1. Collapsible menus on the left hand side.
2. Drop down menus from the nav bar (right hand side)

I tried to use your MyLayout (demo code: https://marmelab.com/admin-on-rest//Theming.html#using-a-custom-layout) 

I encountered error:
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

This happens the moment I include <Admin **appLayout={MyLayout}**  restClient={restClient} authClient={authClient} dashboard={dashboard} catchAll={pageNotFound} >

Problem goes away when I take out **appLayout={MyLayout}**

I do have import MyLayout from './MyLayout' in App.js

Any thoughts/pointers are appreciated.

**Comment by djhi** [comment] 2017-09-16 07:29
Duplicate of #1025. Sorry we forgot to update this part of the documentation. Please refer to the linked issue for more info

**Comment by fzaninotto** [comment] 2017-10-03 12:06
Documentation updated in reference to #1025, closing this one as duplicate.

As for trying your own implementation, I advise you to ask for help in StackOverflow.

**Closed by fzaninotto** 2017-10-03 12:06 UTC
