### ISSUE TITLE
Empty fields when going out of Show view (with TabbedForm inside) in the Edit view

### ISSUE THREAD

**Issue by MaxAlex666** [marmelab/admin-on-rest#1669] opened 2018-03-18 10:10 UTC
**What you were expecting:**
After the transition from the form Show in Edit form fields must contain values.

**What happened instead:**
After the transition from the form Show in Edit form all fields empty!

**Steps to reproduce:**
If the Show form contains TabbedForm, then after going to the Edit form all fields are displayed empty,
the transition from the List form to the Edit form displays all fields filled!

**Other information:**
Replacing TabbedForm with SimpleShowLayout solves the problem.

**Environment**
* Admin-on-rest version: 1.4.0
* Last version that did not exhibit the issue (if applicable): 1.3.4 ???
* React version: 16.2.0
* Browser: Chrome 65.0.3325.162
* Stack trace (in case of a JS error): no errors in the console!

![demo2](https://user-images.githubusercontent.com/16526424/37564757-0826f8b0-2abe-11e8-8ca9-696d52fa4efb.gif)

**Comment by mbchoa** [comment] 2018-03-22 23:34
@MaxAlex666 Getting the same issue.  It looks like the root cause is from a `@@redux-form/DESTROY` action being called when the route changes.

**Comment by fzaninotto** [comment] 2018-03-30 16:08
I think it's a duplicate of #1613

**Closed by fzaninotto** 2018-03-30 16:08 UTC
