### ISSUE TITLE
Problem with rerendering inside SimpleForm

### ISSUE THREAD

**Issue by vantox** [marmelab/admin-on-rest#1104] opened 2017-09-28 07:57 UTC
hello,
i was using AOR 1.2.2 for site settings panel.
Tricky part was that those settings can have different types: string,int,bool, array of string, int etc
I managed to do this by connecting record from store and using this code:

```jsx
const SettingsEdit = (props) => {
  return (
    <Edit actions={<SettingsEditActions {...props} />} title={<SettingsTitle />} {...props}>
      <SimpleForm toolbar={<EditToolbar />}>
        <TextField source="description" />
        <DisabledInput elStyle={{ width: '100%' }} label="Default value" source="defaultValue" />
        {renderCountryValue(props)}
      </SimpleForm>
    </Edit>
  );
};

const renderCountryValue = (prop) => {
  const record = prop.record;
  if (record) {
    if (record.multilang) {
      // countryValue will be a dict with locale keys
      // TODO Multilang fields temporary disabled in restClient
      return null;
    }
    // countryValue will be single value or array
    if (record.schema.type === 'array') {
      // countryValue will be single array
      if (record.schema.items.type === 'string') {
        return <LongTextInput format={v => v.join()} parse={v => v.split(',')} label="Value" source="countryValue" />;
      }
      if (record.schema.items.type === 'integer') {
        return <LongTextInput format={v => v.join()} parse={v => v.split(',')} validate={validateIntegerArray} label="Value" source="countryValue" />;
      }
    }
    // countryValue will be single value
    if (record.schema.type === 'string') {
      return <TextInput label="Value" source="countryValue" />;
    }
    if (record.schema.type === 'integer') {
      return <NumberInput label="Value" source="countryValue" />;
    }
    if (record.schema.type === 'boolean') {
      return <BooleanInput label="Value" source="countryValue" />;
    }

    return <LongTextInput label="Value" source="countryValue" />;
  }
  return <TextInput label="Value" source="countryValue" />;
};
```

It was working well untill i tried updating AOR to 1.3.1 then it stopped.
What i noticed is that in first render there is no record so it renders default TextInput but on second render when there is record it doesn't rerender this Input into correct type like NumberInput or etc. 
I tried to debug it and programm come to place when it should render other  Input but nothing happen on screen.
Any ideas or workarounds?

**Comment by fzaninotto** [comment] 2017-09-29 09:05
Hi, and thanks for your question. As explained in the [admin-on-rest contributing guide](https://github.com/marmelab/admin-on-rest/blob/master/CONTRIBUTING.md), the right place to ask a "How To" question, get usage advice, or troubleshoot your own code, is [StackOverFlow](http://stackoverflow.com/questions/tagged/admin-on-rest).

This makes your question easy to find by the core team, and the developer community. Unlike Github, StackOverFlow has great SEO, gamification, voting, and reputation. That's why we chose it, and decided to keep GitHub issues only for bugs and feature requests.

So I'm closing this issue, and inviting you to ask your question at:

http://stackoverflow.com/questions/tagged/admin-on-rest

And once you get a response, please continue to hang out on the admin-on-rest channel in StackOverflow. That way, you can help newcomers and share your expertise!

**Closed by fzaninotto** 2017-09-29 09:05 UTC

**Comment by vantox** [comment] 2017-09-29 13:05
You think that is not a bug if something worked before 1.3.1 and now don't?

**Comment by fzaninotto** [comment] 2017-09-29 13:23
The proper way to achieve what you're trying to do is to write a custom input component, [as explained in the doc](https://marmelab.com/admin-on-rest/Inputs.html#writing-your-own-input-component). 

Calling a function in Form Children wasn't a documented or a supported feature. We can't consider this a regression since we've never even known it was possible ;)

**Comment by zifnab87** [comment] 2017-10-01 15:19
seems related to: #1116
