### ISSUE TITLE
[RFC] Pagination shows "NaN - NaN of NaN" during list refresh.

### ISSUE THREAD

**Issue by toryrm** [marmelab/admin-on-rest#982] opened 2017-08-29 19:04 UTC
I've noticed this whenever I refresh the list, and found that the fix is adding a simple `isNaN(total)` check in a conditional at line 102 in `src/mui/list/Pagination.js`:
`if (total === 0 || isNaN(total)) return null;`

Can create a PR if this is deemed appropriate, but wanted to create an issue first.

**Comment by djhi** [comment] 2017-08-31 16:14
I can't reproduce it on the [demo app](https://marmelab.com/admin-on-rest-demo/#/customers)

**Comment by fzaninotto** [comment] 2017-09-01 07:01
Can you please provide a minimal reproductible test case, as explained in the CONTRIBUTING.md guidelines?

**Comment by than** [comment] 2017-09-01 20:55
Having the same issue using the latest release.

**Comment by djhi** [comment] 2017-09-04 07:41
Still can't reproduce this on the demo app

**Comment by than** [comment] 2017-09-06 19:23
If you drop the offset/perPage params from the URL request you can see this reproduced in the demo app. AOR doesn't seem to imply defaults for offset and returns NaN. 
https://marmelab.com/admin-on-rest-demo/#/customers?filter=%7B%22q%22%3A%22edwards%22%7D

![screen shot 2017-09-06 at 2 23 28 pm](https://user-images.githubusercontent.com/510790/30130487-f83bf4ba-930e-11e7-9ce5-801122e56457.png)

**Comment by than** [comment] 2017-09-06 19:41
Or for an example that doesn't require URL manipulation, follow these steps: 

1) Click into the Categories List ( https://marmelab.com/admin-on-rest-demo/#/categories ) 

2) Click on any of the Products buttons

![](http://than.d.pr/ayNjRP.png)

**Comment by fzaninotto** [comment] 2017-09-12 09:34
I'm not sure it's a bug. If you update the URL yourself, you may expect strange side effects. As for the demo, it's the Products list button that doesn't include the pagination elements. It was fixed in https://github.com/marmelab/admin-on-rest-demo/commit/cdfad428509c5ec8a3ff5edc2e981d81663559f2, but not yet deployed.

**Comment by zifnab87** [comment] 2017-09-16 16:52
@fzaninotto by default aren't we landing to `page=1` ? Couldn't have that as default even when it is not provided through the url or through `FlatButton` search? From my earlier tests I remember that if `page` is there that makes it work without the need of `perPage`

**Comment by fzaninotto** [comment] 2017-09-20 13:04
OK, I get the problem.

When there is no query string, aor uses the resource list's `query` object (from the Redux store), which has a default page value of 1. So when navigating from the menu, there is no bug.

When the user applies a filter, a sort, or changes the page, the URL changes, and includes a query string. In that case, aor takes the value from the query string and ignores the `query` value. But it only works if the query string is complete.

To put it otherwise, if you create a link to a filtered list, you MUST include `sort`, `order`, `page`, and `filter` keys.

Adding support for a default param value is a nice idea, but in my opinion it's an enhancement request.

**Comment by Toosick** [comment] 2017-11-01 01:26
@zifnab87 @fzaninotto https://github.com/marmelab/admin-on-rest/pull/1191 should fix the default page problem.

**Comment by fzaninotto** [comment] 2017-12-14 10:25
Fixed by #1288

**Closed by fzaninotto** 2017-12-14 10:25 UTC
Labels: enhancement
