### ISSUE TITLE
Migration to Material-UI@v1?

### ISSUE THREAD

**Issue by oliviertassinari** [marmelab/admin-on-rest#1106] opened 2017-09-28 16:13 UTC
Hey, we have just started using this project after considering alternatives like [Forest Admin](https://www.forestadmin.com/). **It's great!** 👏 
The main paint point we faced so far is keeping old material-ui version v0.x work with the upcoming one v1.x.

Do you have any plan upgrading the version of Material-UI? I have started adding [a migration guide](https://material-ui-1dab0.firebaseapp.com/guides/migration-v0.x) for this purpose in the documentation.

**Comment by djhi** [comment] 2017-09-28 16:17
Thanks!

Closing as it's a duplicate of #924.

In short, yes, but when it will be released.

Keep up the good work !

**Closed by djhi** 2017-09-28 16:17 UTC

**Comment by oliviertassinari** [comment] 2017-09-28 16:19
Alright you want to wait for the official release. That shouldn't take more than 6 months. Thanks for the answer :).

**Comment by djhi** [comment] 2017-09-28 16:24
6 months ?! :scream: Where's the whip emote when you need it ? :stuck_out_tongue: 

PS: I already tried it on another project, you did an amazing job on v1! Can't wait for the release!

**Comment by oliviertassinari** [comment] 2017-09-28 16:28
@djhi Well I have already been using v1 for a year now. The thing is that we want to keep the issue flow under control, making it non-beta will mean more people frustration. So, I want to wait the end of the year to release it. The v1.x has around 15% market share of the v0.x. I also want to wait having a higher figure.

**Comment by djhi** [comment] 2017-09-28 16:30
Does it mean that the API won't change anymore ?

**Comment by TankiLM** [comment] 2017-09-28 17:03
Hey @oliviertassinari, just curious about what made you switch from ForestAdmin to material-ui? Happy to discuss it with you!

**Comment by oliviertassinari** [comment] 2017-09-28 18:25
Hi @TankiLM, I didn't switch from ForestAdmin to Material-UI. We have picked admin-on-rest over ForestAdmin for the following reasons:
1. We find it obviously too expensive in comparison to the alternatives. As far as we have been documenting ourselves, `admin-on-rest` is going to provide more or less the same value for us with a lower cost. We have to spend a day or two to [wire Objection](https://github.com/Vincit/objection-rest) with admin-on-rest. (@djhi we use graphql for the customer-facing API, but support for it seems low right now, so we picked a REST generator)
2. We have been migrating away from [Sequelize](https://github.com/sequelize/sequelize) to [Objection](https://github.com/Vincit/objection.js). Using the database backend isn't an option. We want to maximize data consistency.

**Comment by djhi** [comment] 2017-09-28 18:46
About GraphQL support, did you check [aor-graphql](https://github.com/marmelab/aor-graphql) ?

We still have a lot of work here, mainly on documentation but it should be usable. We implemented the demo app using the GraphCool API.

We don't currently have any client projects using gql so we haven't battle tested yet

**Comment by oliviertassinari** [comment] 2017-09-28 19:26
@djhi I have seen it. But we would rather use something battle tested :).

**Comment by TankiLM** [comment] 2017-09-29 08:20
Hey @oliviertassinari Thanks for your answer. 

We offer a free version with an unlimited number of activities and no restriction on the number of users which means you can use Forest without ever having to upgrade. We do offer, however, a pro plan including features aimed at larger teams and more operational intensive businesses. For more information, please refer to [our pricing page](https://www.forestadmin.com/pricing/)

We do support Sequelize for Node.js but not objection.js which means Forest won’t be suited for your project as of now.

**Comment by fzaninotto** [comment] 2017-09-29 08:46
@oliviertassinari Would your team have some dev time to allocate to admin-on-rest to help the transition?

That would really speed things up, since your people already know the 1.0 very well.

**Comment by oliviertassinari** [comment] 2017-09-29 12:21
@fzaninotto It's unlikely it will happen anytime soon as I'm already pretty busy with the Material-UI issues handling. Regarding our team. We will see how well admin-on-rest covers our use cases. The more we depend on it, the more likely we will help.

**Comment by fzaninotto** [comment] 2017-09-29 13:24
OK, it was worth asking ;)
