### ISSUE TITLE
Don't use one-to-many,many-to-many model in client side

### ISSUE THREAD

**Issue by WangLarry** [marmelab/admin-on-rest#481] opened 2017-03-20 13:58 UTC
The consistency of data is complex problem, in client side  especially.
Current implement of data reducer in AOR have some problems(BUGS):
1. After the refresh of cached data (in data.js ), some foreign reference( in ids.js) will be invalid;
2. If a record of one resource is be deleted,  foreign reference to it ( in ids.js) will be invalid;
...

For slove these problems,  we need keep  consistency of data in client side AND to server side.
This implement is complex, and is difficult task.

My suggest:
In server side, try to embed foreign reference data, package all data  to send client.
In client side, try not to reference foreign data in others resource, and try not to cache it.

**Comment by fzaninotto** [comment] 2017-03-20 14:54
I don't understand your point. Can you list actual bugs with, for each bug, a step-by-step scenario, what you expect to see, what you actually see, and possibly some code to illustrate your point? 

As for keeping consistency of data across endpoints connected only via HTTP, if you ever find a solution, you'll be a millionaire. As for us, we're not that interested in money, so we won't try to find one in admin-on-rest. Also, you might be interested in https://github.com/marmelab/aor-simple-graphql-client.

I'm closing this one ; please open one issue per bug.

**Closed by fzaninotto** 2017-03-20 14:54 UTC

**Comment by WangLarry** [comment] 2017-03-20 15:10
Sorry for poor english.
It is not about money!

One bug:
/**
 * Add new records to the pool, and remove outdated ones.
 *
 * This is the equivalent of a stale-while-revalidate caching strategy:
 * The cached data is displayed before fetching, and stale data is removed
 * only once fresh data is fetched.
 */
const addRecords = (newRecords = [], oldRecords) => {
    ....

will delete outdated records, but some reference ids still exists in 'one to many' redux state.

**Comment by fzaninotto** [comment] 2017-03-20 15:13
That's not a bug, because the data is refetched all the time (e.g. each time you go to an Edit or Show view, the server data is fetched again). After leaving the page, the data from the store only serves for optimistic rendering.

**Comment by WangLarry** [comment] 2017-03-20 15:35
e.g: In list page, click one page button, then create this page component, which contain one-to-many reference, then call 'crudGetOneReference', then get 'GET_MANY_REFERENCE' action, call  addRecords, will delete outdated data, which may be used in this list page.

**Comment by WangLarry** [comment] 2017-03-20 15:41
Sorry, I read codes carefully again.

**Comment by fzaninotto** [comment] 2017-03-20 16:37
I still don't understand, can you try again using the blog example? The Post Edit page has a ReferenceManyField on comments, what is wrong with it?

**Comment by WangLarry** [comment] 2017-03-21 00:23
catch it:

in ids.js, chang this code:

switch (type) {
    case CRUD_GET_LIST_SUCCESS:
 ++>   case CRUD_GET_MANY_SUCCESS:
 ++>   case CRUD_GET_MANY_REFERENCE_SUCCESS:

**Comment by fzaninotto** [comment] 2017-04-05 12:53
I don't understand your comment. You point implementation details, but what is wrong in the current *behavior* according to you?
