### ISSUE TITLE
ReferenceInput not using source prop

### ISSUE THREAD

**Issue by Maxi-Di-Mito** [marmelab/admin-on-rest#456] opened 2017-03-16 14:55 UTC
Hi, 
    I found a problem when using the refenceInput with the selectInput. I have this form:

``` xml
<Create  {...props} title="Nuevo Usuario">
        <SimpleForm>
            <TextInput label="Usuario" source="username" validation={{ require: true }}/>
            <TextInput label="Nombre" source="name" />
            <TextInput label="Apellido" source="lastName" />
            <ReferenceInput label="Rol" source="roleId" reference="roles" allowEmpty validation={{ require: true }}>
                <SelectInput optionText="name" />
            </ReferenceInput>            
        </SimpleForm>
    </Create>
```

When i submit the object that it send is like this: 
``` javascript
{
    username: 'someUsername',
    name: 'someName',
    lastName: 'someLastname',
    id: 'the id of the referenceInput'
}
```

I was expecting that the field 'id' was named 'roleId' as the source prop of the referenceInput.

Something strange is that when i add another referenceInput on the same form it sends the object using the source prop of each referenceInput as expected.

**Comment by fzaninotto** [comment] 2017-03-16 15:08
I can't reproduce the problem. For instance in [the demo](https://marmelab.com/admin-on-rest-demo/#/commands/550?_k=hilsda), when you edit the customer of an order, it properly sends the customer id in `customer_id` and not in `id`.

There must be something else that goes wrong in your code, perhaps in your `restClient`?

As it works for me, I'm closing this. Feel free to reopen if you can provide pore context.

**Closed by fzaninotto** 2017-03-16 15:08 UTC

**Comment by Maxi-Di-Mito** [comment] 2017-03-16 15:49
I checked the code of the demo and there it uses the ReferenceInput with the AutocompleteInput not the SelectInput. Is not the same scenario.
