### ISSUE TITLE
Validation error for  TextInput raises errors in console in 2.0.0-beta*

### ISSUE THREAD

**Issue by aaxx** [marmelab/admin-on-rest#1693] opened 2018-03-23 17:44 UTC
**What you were expecting:**
Validation error is shown up in TextInput

**What happened instead:**
TextInput is red, no error displayed, a bunch of errors in console

**Steps to reproduce:**
On the sandbox below, go to Edit Post, clear the "Title" field, will have error stacktrace similar to the reported.

**Related code:**
* CodeSandbox: https://codesandbox.io/s/q7r99p8349

```
      <TextInput source='name' label='Name' validate={required()}/>
```

**Other information:**

Dev Tools Console snapshot:
https://monosnap.com/file/ObvMWGa4PYVeJwhItOH1QHL5sVUhIm

**Environment**

* Admin-on-rest version: 2.0.0-beta4
* React version: 16
* Browser: Firefox
* Stack trace (in case of a JS error):
Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it.
    in p (created by FormHelperText)
    in FormHelperText (created by WithStyles(FormHelperText))
    in WithStyles(FormHelperText) (created by TextField)
    in div (created by FormControl)
    in FormControl (created by WithStyles(FormControl))
    in WithStyles(FormControl) (created by TextField)
    in TextField (created by TextInput)
    in TextInput (created by ConnectedField)
    in ConnectedField (created by Connect(ConnectedField))
    in Connect(ConnectedField) (created by Field)
    in Field (created by FormField)
    in FormField (created by Connect(FormField))
    in Connect(FormField) (created by WithFormField)
    in WithFormField (at index.js:38)
    in div (created by FormInput)
    in FormInput (created by WithStyles(FormInput))
    in WithStyles(FormInput) (created by FormTab)
    in span (created by FormTab)
    in FormTab (at index.js:35)
    in div (created by TabbedForm)
    in form (created by TabbedForm)
    in TabbedForm (created by WithStyles(TabbedForm))
    in WithStyles(TabbedForm) (created by Form(WithStyles(TabbedForm)))
    in Form(WithStyles(TabbedForm)) (created by Connect(Form(WithStyles(TabbedForm))))
    in Connect(Form(WithStyles(TabbedForm))) (created by ReduxForm)
    in ReduxForm (created by TranslatedComponent(undefined))
    in TranslatedComponent(undefined) (created by Connect(TranslatedComponent(undefined)))
    in Connect(TranslatedComponent(undefined)) (at index.js:34)
    in div (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper) (created by Card)
    in Card (created by EditView)
    in div (created by EditView)
    in EditView (created by EditController)
    in EditController (created by TranslatedComponent(undefined))
    in TranslatedComponent(undefined) (created by Connect(TranslatedComponent(undefined)))
    in Connect(TranslatedComponent(undefined)) (created by Edit)
    in Edit (at index.js:33)
    in ExchangeEdit (created by WithPermissions)
    in WithPermissions (created by Connect(WithPermissions))
    in Connect(WithPermissions) (created by getContext(Connect(WithPermissions)))
    in getContext(Connect(WithPermissions)) (created by Route)
    in Route (created by Resource)
    in Switch (created by Resource)
    in Resource (created by Connect(Resource))
    in Connect(Resource) (at App.js:20)
    in Route (created by RoutesWithLayout)
    in Switch (created by RoutesWithLayout)
    in RoutesWithLayout (created by Route)
    in div (created by Layout)
    in main (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by WithStyles(Layout))
    in WithStyles(Layout) (created by Connect(WithStyles(Layout)))
    in Connect(WithStyles(Layout)) (created by LayoutWithTheme)
    in MuiThemeProvider (created by LayoutWithTheme)
    in LayoutWithTheme (created by Route)
    in Route (created by CoreAdminRouter)
    in Switch (created by CoreAdminRouter)
    in div (created by CoreAdminRouter)
    in CoreAdminRouter (created by Connect(CoreAdminRouter))
    in Connect(CoreAdminRouter) (created by getContext(Connect(CoreAdminRouter)))
    in getContext(Connect(CoreAdminRouter)) (created by Route)
    in Route (created by CoreAdmin)
    in Switch (created by CoreAdmin)
    in Router (created by ConnectedRouter)
    in ConnectedRouter (created by CoreAdmin)
    in TranslationProvider (created by withContext(TranslationProvider))
    in withContext(TranslationProvider) (created by Connect(withContext(TranslationProvider)))
    in Connect(withContext(TranslationProvider)) (created by CoreAdmin)
    in Provider (created by CoreAdmin)
    in CoreAdmin (created by withContext(CoreAdmin))
    in withContext(CoreAdmin) (at App.js:16)
    in App (at index.js:5)
index.js:2178

**Comment by fzaninotto** [comment] 2018-03-29 15:57
I can't reproduce the issue you describe:

- in your sandbox (https://codesandbox.io/s/q7r99p8349), the title field isn't required, and it uses react-admin beta 1
- I forked it to make the title required and to use react-admin beta 4 (https://codesandbox.io/s/040r67zo80), and there is no error when I empty the field, in Chrome and Firefox.

My assumption is that you haven't upgraded all your `validate` props, and that your `PostEditForm` still contains some `validate={required}` instead of `validate={required()}`.

So I'm closing this issue as "works for me", feel free to reopen if you can reproduce it based on my sandbox.

**Closed by fzaninotto** 2018-03-29 15:57 UTC
