### ISSUE TITLE
SyntaxError when trying to run basic unit test from `create-react-app`

### ISSUE THREAD

**Issue by demetriusnunes** [marmelab/admin-on-rest#160] opened 2016-11-21 13:59 UTC
When I try to run unit tests from `create-react-app` on a single resource as follows:
```
      <Admin restClient={restClient('/api')}>
        <Resource name="accounts" list={AccountList} edit={AccountEdit} create={AccountCreate} remove={AccountDelete} ></Resource>
      </Admin>
```

I get the error as follows:

```
● renders without crashing

    SyntaxError

      at LocationImpl.replace (node_modules/jsdom/lib/jsdom/living/window/Location-impl.js:225:13)
      at Location.replace (node_modules/jsdom/lib/jsdom/living/generated/Location.js:39:29)
      at Object.replaceHashPath (node_modules/history/lib/DOMUtils.js:37:19)
      at ensureSlash (node_modules/history/lib/createHashHistory.js:40:13)
      at startHashChangeListener (node_modules/history/lib/createHashHistory.js:103:5)
      at Object.listen (node_modules/history/lib/createHashHistory.js:167:57)
      at Object.listen (node_modules/history/lib/useBasename.js:98:22)
      at Object.listen (node_modules/history/lib/useQueries.js:108:22)
      at syncHistoryWithStore (node_modules/react-router-redux/lib/sync.js:104:36)
      at Admin (node_modules/admin-on-rest/lib/Admin.js:74:62)
```

I'm guessing it has something to do with the router. Inspecting the `url` value that reaches `jsdom/living/window/Location-impl.js:225`, I see it's: `blank#/`

Help?

**Comment by fzaninotto** [comment] 2016-11-23 15:06
I don't know which REST client you use. Maybe try with an absolute URL?

**Comment by demetriusnunes** [comment] 2016-11-23 18:35
Ok, tried that, same error.

Also tried using the built-in `jsonServerRestClient` like this:

`<Admin restClient={jsonServerRestClient('http://jsonplaceholder.typicode.com')}>`

Same error.

**Comment by fzaninotto** [comment] 2016-11-29 16:36
Can you paste your version of the following packages:

* `react`
* `react-dom`
* `history`
* `react-router-redux`

**Comment by demetriusnunes** [comment] 2016-11-29 18:10
* react: 15.3.2
* react-dom: 15.3.2
* history: 2.1.2
* react-router-redux: 4.0.7

**Comment by demetriusnunes** [comment] 2016-11-29 20:30
Oh, one important detail: I ejected the app from create-react-app to be able to customize the proxy settings. But that was it.

**Comment by fzaninotto** [comment] 2016-11-30 10:53
I can't reproduce the issue. Does the app works through a web browser?

**Comment by demetriusnunes** [comment] 2016-11-30 12:01
Yes, everything works. Only the test fail.

**Comment by demetriusnunes** [comment] 2016-11-30 12:02
If I'm the only one having this, then it must be something particular to my environment. I think we can close this.

**Comment by fzaninotto** [comment] 2016-11-30 12:04
What type of test is it? unit test with enzyme and shallow rendering?

**Comment by demetriusnunes** [comment] 2016-11-30 13:11
It's this one: https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/src/App.test.js

**Comment by fzaninotto** [comment] 2016-11-30 14:35
Oh, and this is run by a browser? Then there is no difference with a web app - and no reason why a web app should work and this test fail...

I've released a new version, can you test again?

**Comment by fzaninotto** [comment] 2016-12-21 13:38
No news for some time, closing.

**Closed by fzaninotto** 2016-12-21 13:38 UTC
