### ISSUE TITLE
NullableBooleanInput strange behavior

### ISSUE THREAD

**Issue by remi13131** [marmelab/admin-on-rest#652] opened 2017-05-10 14:23 UTC
Using AOR 1.0.1 (IDK if this behavior was here on previous releases) 

NullableBooleanInput will not accept the "No" value at first. I have to choose "Yes" then to choose "No" again to be able to choose "No". 
Then, when "No" is selected, it is impossible to get it to choose null instead. I also have to choose "Yes" then to choose null. 

Gif from https://marmelab.com/admin-on-rest-demo/#/customers/784 : 
![out](https://cloud.githubusercontent.com/assets/11832241/25903516/f0782be2-359c-11e7-9361-45a284cc6f81.gif)

**Comment by djhi** [comment] 2017-05-10 14:27
Reproduced

**Comment by djhi** [comment] 2017-05-12 08:50
This is in fact due to a bug in redux-form which is described here: https://github.com/erikras/redux-form/issues/1993.

After checking the code, it seems that the revert has not been done, neither in 6.2.0 no the latest. We'll have to wait for it.

**Comment by wesley6j** [comment] 2017-05-27 23:24
Interesting. The selected value, whether it is null or false, is properly saved into redux store. However, select input does not know that the value is updated.

On the other hand, if the choice is saved in the input's internal state, the selected value is updated properly.

So, the problem can definitely be fixed with a internal state in the input.

**Closed** 2017-06-01 15:39 UTC
Labels: bug
