### ISSUE TITLE
Add ability to allow change button label for ShowButton/CreateButton/SaveButton/ListButton/EditButton/DeleteButton

### ISSUE THREAD

**Issue by FallDi** [marmelab/admin-on-rest#269] opened 2017-02-01 12:05 UTC
Currently label of button is hardcoded inside. Please add ability to customize it.

```
const ShowButton = ({ basePath = '', record = {} }) => <FlatButton
    primary
    label="Show"
    icon={<ImageEye />}
    containerElement={<Link to={`${linkToRecord(basePath, record.id)}/show`} />}
    style={{ overflow: 'inherit' }}
/>;
```

**Comment by fzaninotto** [comment] 2017-02-01 13:19
Duplicate of #230, already implemented in #234 (in the `next` branch)

**Closed by fzaninotto** 2017-02-01 13:19 UTC
