### ISSUE TITLE
Version 1.0.0 - Error refreshing

### ISSUE THREAD

**Issue by chemitaxis** [marmelab/admin-on-rest#604] opened 2017-04-26 16:51 UTC
In new version 1.0.0, if you are listing items with filters enabled, and you press refresh, the page is refreshed, the filters is cleaned, but the request is the same like filters are enabled.
![ezgif-3-4827e7fbce](https://cloud.githubusercontent.com/assets/1420409/25446256/52c2210a-2ab1-11e7-9e38-eedb99f62a15.gif)

Code of my Custom Filter: 

```
const CustomInspirationFilter = props => (
  <Filter {...props}>
    <SelectInput
      label="Select Category"
      source="Category"
      choices={customInspirationType}
      optionText="name"
      optionValue="_id"
      alwaysOn
    />
    <SelectInput
      label="Select Language"
      source="Language"
      choices={typeLanguage}
      optionText="name"
      optionValue="_id"
      alwaysOn
    />
    <TextInput label="Search by Id" source="id" />
  </Filter>
);
```

If I remove the alwaysOn prop it works fine.

Thanks.

**Comment by chemitaxis** [comment] 2017-04-27 19:43
Ok, I have tested again, and the alwaysOn is working bad too. Thanks

**Comment by fzaninotto** [comment] 2017-05-02 15:32
Confirmed, that's a regression

**Comment by chemitaxis** [comment] 2017-05-02 15:33
Thanks for the feedback...

**Comment by fzaninotto** [comment] 2017-05-02 16:09
In fact, it's a duplicate of #416

**Closed by fzaninotto** 2017-05-02 16:09 UTC
Labels: bug

**Comment by chemitaxis** [comment] 2017-05-03 07:11
Hi @fzaninotto in the previous version, I did not have this error... but, ok.
